# Pandas primeiros comandos

In [ ]:
pip install pandas # Instalação, apenas a primeira vez

In [2]:
# Importando o pacote
import pandas as pd

*Representação da tabela de dados dos Pandas*

In [3]:
# Criando Data Frame Simples
df = pd.DataFrame(
    {
        "Name":[
            "Lionel Messi",
            "Neymar Jr",
            "Cristiano Ronaldo",
        ],
        "Age" : [38, 34, 41],
        "Sex" : ["Male", "Male", "Male"],
    }
)
df

                Name  Age   Sex
0       Lionel Messi   38  Male
1          Neymar Jr   34  Male
2  Cristiano Ronaldo   41  Male

*Só estou interessado em trabalhar com os dados da coluna: Age*

In [4]:
df["Age"]

0    38
1    34
2    41
Name: Age, dtype: int64

In [6]:
# Um pandas não tem rótulos de coluna, pois é apenas uma única coluna de um . A Série tem rótulos de linha.SeriesDataFrame
ages = pd.Series([38,34,41], name = "Age")
ages

0    38
1    34
2    41
Name: Age, dtype: int64

In [10]:
df["Age"].max() # vendo o valor maximo
df["Age"].min() # Vendo o valor minimo

np.int64(34)

In [12]:
# Usando a variavel
ages.max()
ages.min()

np.int64(34)

In [14]:
df.describe() # Estatisticas Basicas do DataFrame

             Age
count   3.000000
mean   37.666667
std     3.511885
min    34.000000
25%    36.000000
50%    38.000000
75%    39.500000
max    41.000000

# Como eu leio e escrevo dados tabulares?

In [44]:
import csv

titanic = pd.read_csv(
    "C:/Users/raphael.eugenio/Desktop/Raphael/Outros/titanic.csv",
    encoding="utf-8-sig",
    quoting=csv.QUOTE_NONE,
    escapechar='\\'
)

In [45]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
"""1",0,3,"""""Braund","Mr. Owen Harris""""",male,22.0,1,0,A/5 21171,7.2500,NaN,"S"""
"""2",1,1,"""""Cumings","Mrs. John Bradley (Florence Briggs Thayer)""""",female,38.0,1,0,PC 17599,71.2833,C85,"C"""
"""3",1,3,"""""Heikkinen","Miss Laina""""",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,"S"""
"""4",1,1,"""""Futrelle","Mrs. Jacques Heath (Lily May Peel)""""",female,35.0,1,0,113803,53.1000,C123,"S"""
"""5",0,3,"""""Allen","Mr. William Henry""""",male,35.0,0,0,373450,8.0500,NaN,"S"""
...,...,...,...,...,...,...,...,...,...,...,...,...
"""887",0,2,"""""Montvila","Rev. Juozas""""",male,27.0,0,0,211536,13.0000,NaN,"S"""
"""888",1,1,"""""Graham","Miss Margaret Edith""""",female,19.0,0,0,112053,30.0000,B42,"S"""
"""889",0,3,"""""Johnston","Miss Catherine Helen """"""""Carrie""""""""""""",female,NaN,1,2,W./C. 6607,23.4500,NaN,"S"""
"""890",1,1,"""""Behr","Mr. Karl Howell""""",male,26.0,0,0,111369,30.0000,C148,"C"""
"""891",0,3,"""""Dooley","Mr. Patrick""""",male,32.0,0,0,370376,7.7500,NaN,"Q"""

In [47]:
titanic.head(8) # Ve as Primeiras 8 linhas do df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
"""1",0,3,"""""Braund","Mr. Owen Harris""""",male,22.0,1,0,A/5 21171,7.2500,NaN,"S"""
"""2",1,1,"""""Cumings","Mrs. John Bradley (Florence Briggs Thayer)""""",female,38.0,1,0,PC 17599,71.2833,C85,"C"""
"""3",1,3,"""""Heikkinen","Miss Laina""""",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,"S"""
"""4",1,1,"""""Futrelle","Mrs. Jacques Heath (Lily May Peel)""""",female,35.0,1,0,113803,53.1000,C123,"S"""
"""5",0,3,"""""Allen","Mr. William Henry""""",male,35.0,0,0,373450,8.0500,NaN,"S"""
"""6",0,3,"""""Moran","Mr. James""""",male,NaN,0,0,330877,8.4583,NaN,"Q"""
"""7",0,1,"""""McCarthy","Mr. Timothy J""""",male,54.0,0,0,17463,51.8625,E46,"S"""
"""8",0,3,"""""Palsson","Master Gosta Leonard""""",male,2.0,3,1,349909,21.0750,NaN,"S"""

In [48]:
titanic.tail(8) # Print the last 8 lines of the df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
"""884",0,2,"""""Banfield","Mr. Frederick James""""",male,28.0,0,0,C.A./SOTON 34068,10.500,NaN,"S"""
"""885",0,3,"""""Sutehall","Mr. Henry Jr""""",male,25.0,0,0,SOTON/OQ 392076,7.050,NaN,"S"""
"""886",0,3,"""""Rice","Mrs. William (Margaret Norton)""""",female,39.0,0,5,382652,29.125,NaN,"Q"""
"""887",0,2,"""""Montvila","Rev. Juozas""""",male,27.0,0,0,211536,13.000,NaN,"S"""
"""888",1,1,"""""Graham","Miss Margaret Edith""""",female,19.0,0,0,112053,30.000,B42,"S"""
"""889",0,3,"""""Johnston","Miss Catherine Helen """"""""Carrie""""""""""""",female,NaN,1,2,W./C. 6607,23.450,NaN,"S"""
"""890",1,1,"""""Behr","Mr. Karl Howell""""",male,26.0,0,0,111369,30.000,C148,"C"""
"""891",0,3,"""""Dooley","Mr. Patrick""""",male,32.0,0,0,370376,7.750,NaN,"Q"""

In [50]:
titanic.dtypes # Verifica o tipo da variável

PassengerId      int64
Survived         int64
Pclass             str
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [ ]:
# Enviando para arquivo .xlsx
titanic.to_excel("titanic.xlsx", sheet_name = "passengers", index = False)

In [ ]:
# Trazendo arquivo em .xlsx
titanic = pd.read_excel("titanic.xlsx", sheet_name= "passengers")

In [54]:
# Resumo Tecnico de um DataFrame
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    str
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     891 non-null    str
dtypes: float64(2), int64(4), str(6)
memory usage: 83.7 KB

# Como faço para selecionar um subconjunto de um DataFrame

In [56]:
# Quero a idade dos passageiros do titanic
ages = titanic["Age"]

ages.head(7)

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
Name: Age, dtype: float64

In [57]:
type(titanic["Age"])

pandas.Series

In [67]:
titanic[["Age","Sex"]].shape

(891, 2)

In [ ]:
# Selecionando 2 ou mais colunas
age_sex = titanic[["Age", "Sex"]]
age_sex.head()

    Age     Sex
0  22.0    male
1  38.0  female
2  26.0  female
3  35.0  female
4  35.0    male

In [ ]:
# Filtrando passageiros acima de 35 anos
above_35 = titanic[titanic["Age"] > 35]
above_35

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,1,"""""Cumings","Mrs. John Bradley (Florence Briggs Thayer)""""",female,38.0,1,0,PC 17599,71.2833,C85,"C"""
6,0,1,"""""McCarthy","Mr. Timothy J""""",male,54.0,0,0,17463,51.8625,E46,"S"""
11,1,1,"""""Bonnell","Miss Elizabeth""""",female,58.0,0,0,113783,26.5500,C103,"S"""
13,0,3,"""""Andersson","Mr. Anders Johan""""",male,39.0,1,5,347082,31.2750,NaN,"S"""
15,1,2,"""""Hewlett","Mrs. (Mary D Kingcome) """"",female,55.0,0,0,248706,16.0000,NaN,"S"""
...,...,...,...,...,...,...,...,...,...,...,...,...
865,1,2,"""""Bystrom","Mrs. (Karolina)""""",female,42.0,0,0,236852,13.0000,NaN,"S"""
871,1,1,"""""Beckwith","Mrs. Richard Leonard (Sallie Monypeny)""""",female,47.0,1,1,11751,52.5542,D35,"S"""
873,0,3,"""""Vander Cruyssen","Mr. Victor""""",male,47.0,0,0,345765,9.0000,NaN,"S"""
879,1,1,"""""Potter","Mrs. Thomas Jr (Lily Alexenia Wilson)""""",female,56.0,0,1,11767,83.1583,C50,"C"""
885,0,3,"""""Rice","Mrs. William (Margaret Norton)""""",female,39.0,0,5,382652,29.1250,NaN,"Q"""

In [71]:
titanic["Age"] > 35

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [73]:
# Tamanho do df criado
above_35.shape

(217, 12)

In [84]:
class_23 = titanic[titanic["Survived"].isin([2, 3])]
class_23

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"""""Braund","Mr. Owen Harris""""",male,22.0,1,0,A/5 21171,7.2500,NaN,"S"""
2,1,3,"""""Heikkinen","Miss Laina""""",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,"S"""
4,0,3,"""""Allen","Mr. William Henry""""",male,35.0,0,0,373450,8.0500,NaN,"S"""
5,0,3,"""""Moran","Mr. James""""",male,NaN,0,0,330877,8.4583,NaN,"Q"""
7,0,3,"""""Palsson","Master Gosta Leonard""""",male,2.0,3,1,349909,21.0750,NaN,"S"""
...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,"""""Sutehall","Mr. Henry Jr""""",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,"S"""
885,0,3,"""""Rice","Mrs. William (Margaret Norton)""""",female,39.0,0,5,382652,29.1250,NaN,"Q"""
886,0,2,"""""Montvila","Rev. Juozas""""",male,27.0,0,0,211536,13.0000,NaN,"S"""
888,0,3,"""""Johnston","Miss Catherine Helen """"""""Carrie""""""""""""",female,NaN,1,2,W./C. 6607,23.4500,NaN,"S"""
890,0,3,"""""Dooley","Mr. Patrick""""",male,32.0,0,0,370376,7.7500,NaN,"Q"""

In [86]:
age_no_na = titanic[titanic["Age"].notna()]
age_no_na.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"""""Braund","Mr. Owen Harris""""",male,22.0,1,0,A/5 21171,7.2500,NaN,"S"""
1,1,1,"""""Cumings","Mrs. John Bradley (Florence Briggs Thayer)""""",female,38.0,1,0,PC 17599,71.2833,C85,"C"""
2,1,3,"""""Heikkinen","Miss Laina""""",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,"S"""
3,1,1,"""""Futrelle","Mrs. Jacques Heath (Lily May Peel)""""",female,35.0,1,0,113803,53.1000,C123,"S"""
4,0,3,"""""Allen","Mr. William Henry""""",male,35.0,0,0,373450,8.0500,NaN,"S"""