In [4]:
# Importando as Bibliotecas
import soccerdata as sd
import pandas as pd
from pathlib import Path

from soccerdata import ClubElo # As forças relativas da equipe em classificações Elo, na maioria das ligas europeias. Recalculado após cada rodada, inclui histórico.
from soccerdata import ESPN # Resultados históricos, estatísticas e escalações.
from soccerdata import FBref # Resultados históricos, escalações e estatísticas agregadas detalhadas para times e jogadores individuais com base em dados da Opta.
from soccerdata import MatchHistory # Resultados históricos, odds de apostas e estatísticas de partidas. O nível de detalhe depende da liga.
from soccerdata import Sofascore # Resultados, calendários, escalações e estatísticas detalhadas para times e jogadores individuais.
from soccerdata import SoFIFA # Pontuações detalhadas sobre todas as habilidades dos jogadores do EA Sports FC.
from soccerdata import Understat # Estatísticas avançadas como xG, xGBuildup e xGChain, e eventos de arremesso com valores xG associados para as principais ligas europeias.
from soccerdata import WhoScored # Resultados históricos, dados de prévia de partidas e dados detalhados de transmissões de eventos Opta para as grandes ligas.

# Extração de Dados

In [5]:
# Criar instância da classe scraper
fbref = sd.FBref()

[05/29/26 16:58:04] INFO     Saving cached data to C:\Users\raphael.eugenio\soccerdata\data\FBref    ]8;id=182835;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=503013;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

[05/29/26 16:58:06] INFO     No seasons provided. Will retrieve data for the last 5 seasons.         ]8;id=82785;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=575280;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#462\462]8;;\

In [6]:
# Criar Dataframes
season_stats = fbref.read_team_season_stats(stat_type="shooting")

                    WARNING  c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\L ]8;id=555542;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=636161;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             ib\site-packages\soccerdata\_common.py:144: UserWarning: Season id
                             "2021" is ambiguous: interpreting as "20-21"
                               warnings.warn(msg, stacklevel=1)

In [7]:
# Criar instância da classe scraper filtrando por ligas e temporadas específicas
fbref = sd.FBref(leagues=["Big 5 European Leagues Combined"], seasons=["2017", "2024"])

# Recuperar dados para as ligas e temporada especificadas
season_stats = fbref.read_team_season_stats(stat_type="shooting")

[05/29/26 16:58:09] INFO     Saving cached data to C:\Users\raphael.eugenio\soccerdata\data\FBref    ]8;id=76932;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=791589;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

In [8]:
sd.FBref.available_leagues()

['Big 5 European Leagues Combined',
 'INT-European Championship',
 "INT-Women's World Cup",
 'INT-World Cup']

In [9]:
# Printa as ligas disponiveis
print(sorted(fbref.available_leagues()))

['Big 5 European Leagues Combined', 'INT-European Championship', "INT-Women's World Cup", 'INT-World Cup']

# Configuração Global

In [10]:
# Definindo caminho
fbref = sd.FBref(
    data_dir=Path(r"C:/Users/raphael.eugenio/Desktop/Raphael/Soccerdata")
)

[05/29/26 16:58:18] INFO     Saving cached data to                                                   ]8;id=396547;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=482016;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\
                             C:\Users\raphael.eugenio\Desktop\Raphael\Soccerdata

[05/29/26 16:58:26] INFO     No seasons provided. Will retrieve data for the last 5 seasons.         ]8;id=332960;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=128663;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#462\462]8;;\

In [11]:
fbref = sd.FBref(
    leagues=["Big 5 European Leagues Combined"],
    seasons=[2024],
    data_dir=Path(r"C:\Users\raphael.eugenio\soccerdata")
)

[05/29/26 16:58:27] INFO     Saving cached data to C:\Users\raphael.eugenio\soccerdata               ]8;id=689440;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=918440;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

# ClubElo

In [12]:
# Dados do ClubElo, mede por Ranking historico
elo = sd.ClubElo()
print(elo.__doc__)

[05/29/26 16:58:38] INFO     Saving cached data to C:\Users\raphael.eugenio\soccerdata\data\ClubElo  ]8;id=571983;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=353599;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

[2026-05-29 16:58:38] INFO     TLSLibrary:_load_library:397 - Successfully loaded TLS library: C:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\tls_requests\bin\tls-client-xgo-1.13.1-windows-amd64.dll

                    INFO     Successfully loaded TLS library:                                      ]8;id=819271;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\tls_requests\models\libraries.py\libraries.py]8;;\:]8;id=782241;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\tls_requests\models\libraries.py#397\397]8;;\
                             C:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\
                             site-packages\tls_requests\bin\tls-client-xgo-1.13.1-windows-amd64.dl
                             l

Provides pd.DataFrames from CSV API at http://api.clubelo.com.

Data will be downloaded as necessary and cached locally in
``~/soccerdata/data/ClubElo``.

Since the source does not provide league names, this class will not filter
by league. League names will be inserted from the other sources where
available. Leagues that are only covered by clubelo.com will have NaN
values.

Parameters
----------
proxy : 'tor' or or dict or list(dict) or callable, optional
    Use a proxy to hide your IP address. Valid options are:
        - "tor": Uses the Tor network. Tor should be running in
          the background on port 9050.
        - str: The address of the proxy server to use.
        - list(str): A list of proxies to choose from. A different proxy will
          be selected from this list after failed requests, allowing rotating
          proxies.
        - callable: A function that returns a valid proxy. This function will
          be called after failed requests, allowing rotating proxies.
no_cache : bool
    If True, will not use cached data.
no_store : bool
    If True, will not store downloaded data.
data_dir : Path
    Path to directory where data will be cached.

In [13]:
current_elo = elo.read_by_date()
current_elo.head()

,rank,country,level,elo,from,to,league
team,,,,,,,
Arsenal,1.0,ENG,1,2065.758057,2026-05-25,2026-05-30,ENG-Premier League
Bayern,2.0,GER,1,2000.870239,2026-05-21,2026-05-31,GER-Bundesliga
Man City,3.0,ENG,1,1969.962524,2026-05-25,2026-05-31,ENG-Premier League
Paris SG,4.0,FRA,1,1964.038452,2026-05-24,2026-05-30,FRA-Ligue 1
Barcelona,5.0,ESP,1,1953.367310,2026-05-24,2026-05-31,ESP-La Liga

In [14]:
barca_elo = elo.read_team_history("Barcelona")
barca_elo.head()

            rank       team country  level          elo         to
from
1939-10-22   NaN  Barcelona     ESP      1  1636.704590 1939-12-03
1939-12-04   NaN  Barcelona     ESP      1  1626.102173 1939-12-10
1939-12-11   NaN  Barcelona     ESP      1  1636.728271 1939-12-17
1939-12-18   NaN  Barcelona     ESP      1  1646.951660 1939-12-24
1939-12-25   NaN  Barcelona     ESP      1  1637.424316 1939-12-31

In [15]:
real_elo = elo.read_team_history("Real Madrid")
real_elo.head()

            rank         team country  level          elo         to
from
1939-10-22   NaN  Real Madrid     ESP      1  1636.704590 1939-12-03
1939-12-04   NaN  Real Madrid     ESP      1  1621.710571 1939-12-10
1939-12-11   NaN  Real Madrid     ESP      1  1616.419678 1939-12-17
1939-12-18   NaN  Real Madrid     ESP      1  1625.154663 1939-12-24
1939-12-25   NaN  Real Madrid     ESP      1  1635.314575 1939-12-31

# ESPN

In [16]:
# Definindo Liga e Temporada
espn = sd.ESPN(leagues = "ENG-Premier League", seasons=2021)
print(espn.__doc__)

[05/29/26 16:58:39] INFO     Saving cached data to C:\Users\raphael.eugenio\soccerdata\data\ESPN     ]8;id=802171;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=590716;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

                    WARNING  c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\L ]8;id=875700;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=314487;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             ib\site-packages\soccerdata\_common.py:144: UserWarning: Season id
                             "2021" is ambiguous: interpreting as "20-21"
                               warnings.warn(msg, stacklevel=1)

Provides pd.DataFrames from JSON api available at http://site.api.espn.com.

Data will be downloaded as necessary and cached locally in
``~/soccerdata/data/ESPN``.

Parameters
----------
leagues : string or iterable, optional
    IDs of leagues to include.
seasons : string, int or list, optional
    Seasons to include. Supports multiple formats.
    Examples: '16-17'; 2016; '2016-17'; [14, 15, 16]
proxy : 'tor' or or dict or list(dict) or callable, optional
    Use a proxy to hide your IP address. Valid options are:
        - "tor": Uses the Tor network. Tor should be running in
          the background on port 9050.
        - str: The address of the proxy server to use.
        - list(str): A list of proxies to choose from. A different proxy will
          be selected from this list after failed requests, allowing rotating
          proxies.
        - callable: A function that returns a valid proxy. This function will
          be called after failed requests, allowing rotating proxies.
no_cache : bool
    If True, will not use cached data.
no_store : bool
    If True, will not store downloaded data.
data_dir : Path
    Path to directory where data will be cached.

*Calendário de Jogos*

In [17]:
# Calendário da temporada inteira
epl_schedule = espn.read_schedule()
epl_schedule

                                                                                           date  \
league             season game
ENG-Premier League 2021   2019-08-09 Liverpool-Norwich City           2019-08-09 19:00:00+00:00
                          2019-08-10 AFC Bournemouth-Sheffield United 2019-08-10 14:00:00+00:00
                          2019-08-10 Burnley-Southampton              2019-08-10 14:00:00+00:00
                          2019-08-10 Crystal Palace-Everton           2019-08-10 14:00:00+00:00
                          2019-08-10 Tottenham Hotspur-Aston Villa    2019-08-10 16:30:00+00:00
...                                                                                         ...
                          2020-07-26 Leicester City-Manchester United 2020-07-26 15:00:00+00:00
                          2020-07-26 Manchester City-Norwich City     2020-07-26 15:00:00+00:00
                          2020-07-26 Newcastle United-Liverpool       2020-07-26 15:00:00+00:00
                          2020-07-26 Southampton-Sheffield United     2020-07-26 15:00:00+00:00
                          2020-07-26 West Ham United-Aston Villa      2020-07-26 15:00:00+00:00

                                                                               home_team  \
league             season game
ENG-Premier League 2021   2019-08-09 Liverpool-Norwich City                    Liverpool
                          2019-08-10 AFC Bournemouth-Sheffield United    AFC Bournemouth
                          2019-08-10 Burnley-Southampton                         Burnley
                          2019-08-10 Crystal Palace-Everton               Crystal Palace
                          2019-08-10 Tottenham Hotspur-Aston Villa     Tottenham Hotspur
...                                                                                  ...
                          2020-07-26 Leicester City-Manchester United     Leicester City
                          2020-07-26 Manchester City-Norwich City        Manchester City
                          2020-07-26 Newcastle United-Liverpool         Newcastle United
                          2020-07-26 Southampton-Sheffield United            Southampton
                          2020-07-26 West Ham United-Aston Villa         West Ham United

                                                                               away_team  \
league             season game
ENG-Premier League 2021   2019-08-09 Liverpool-Norwich City                 Norwich City
                          2019-08-10 AFC Bournemouth-Sheffield United   Sheffield United
                          2019-08-10 Burnley-Southampton                     Southampton
                          2019-08-10 Crystal Palace-Everton                      Everton
                          2019-08-10 Tottenham Hotspur-Aston Villa           Aston Villa
...                                                                                  ...
                          2020-07-26 Leicester City-Manchester United  Manchester United
                          2020-07-26 Manchester City-Norwich City           Norwich City
                          2020-07-26 Newcastle United-Liverpool                Liverpool
                          2020-07-26 Southampton-Sheffield United       Sheffield United
                          2020-07-26 West Ham United-Aston Villa             Aston Villa

                                                                       game_id  \
league             season game
ENG-Premier League 2021   2019-08-09 Liverpool-Norwich City             541844
                          2019-08-10 AFC Bournemouth-Sheffield United   541840
                          2019-08-10 Burnley-Southampton                541841
                          2019-08-10 Crystal Palace-Everton             541839
                          2019-08-10 Tottenham Hotspur-Aston Villa      541837
...                                                                        ...
                          2020-07-26 Leicester City-Manchester United   541469
                          2020-07-26 Manchester City-Norwich City       541470
                          2020-07-26 Newcastle United-Liverpool         541468
                          2020-07-26 Southampton-Sheffield United       541471
                          2020-07-26 West Ham United-Aston Villa        541465

                                                                      league_id
league             season game
ENG-Premier League 2021   2019-08-09 Liverpool-Norwich City               eng.1
                          2019-08-10 AFC Bournemouth-Sheffield United     eng.1
                          2019-08-10 Burnley-Southampton                  eng.1
                          2019-08-10 Crystal Palace-Everton               eng.1
                          2019-08-10 Tottenham Hotspur-Aston Villa        eng.1
...                                                                         ...
                          2020-07-26 Leicester City-Manchester United     eng.1
                          2020-07-26 Manchester City-Norwich City         eng.1
                          2020-07-26 Newcastle United-Liverpool           eng.1
                          2020-07-26 Southampton-Sheffield United         eng.1
                          2020-07-26 West Ham United-Aston Villa          eng.1

[380 rows x 5 columns]

*Estatísticas do jogo*

In [18]:
# Estatisticas dos jogos por partida selecionando por id
matchsheet = espn.read_matchsheet(match_id=541470)
matchsheet.head()

                                                                                   is_home  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City     True
                                                                  Norwich City       False

                                                                                            venue  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City  Etihad Stadium
                                                                  Norwich City     Etihad Stadium

                                                                                   attendance  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City           0
                                                                  Norwich City              0

                                                                                  capacity  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City     None
                                                                  Norwich City        None

                                                                                                                              roster  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City  [{'active': True, 'starter': True, 'jersey': '...
                                                                  Norwich City     [{'active': True, 'starter': True, 'jersey': '...

                                                                                  fouls_committed  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City               7
                                                                  Norwich City                  4

                                                                                  yellow_cards  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City            1
                                                                  Norwich City               1

                                                                                  red_cards  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City         0
                                                                  Norwich City            0

                                                                                  offsides  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City        0
                                                                  Norwich City           2

                                                                                  won_corners  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City           9
                                                                  Norwich City              0

                                                                                   ...  \
league             season game                                    team             ...
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City  ...
                                                                  Norwich City     ...

                                                                                  total_long_balls  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City               45
                                                                  Norwich City                  63

                                                                                  accurate_long_balls  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City                  35
                                                                  Norwich City                     26

                                                                                  longball_pct  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City          0.8
                                                                  Norwich City             0.4

                                                                                  blocked_shots  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City             9
                                                                  Norwich City                0

                                                                                  effective_tackles  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City                 8
                                                                  Norwich City                    5

                                                                                  total_tackles  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City            12
                                                                  Norwich City               14

                                                                                  tackle_pct  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City        0.7
                                                                  Norwich City           0.4

                                                                                  interceptions  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City            10
                                                                  Norwich City               14

                                                                                  effective_clearance  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City                   5
                                                                  Norwich City                     26

                                                                                  total_clearance
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City               5
                                                                  Norwich City                 26

[2 rows x 33 columns]

*Formações de Jogo*

In [19]:
# Formação de Jogo por ID
lineups = espn.read_lineup(match_id=541470)
lineups

                                                                                                       is_home  \
league             season game                                    team            player
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City Aymeric Laporte         True
                                                                                  Benjamin Mendy          True
                                                                                  Bernardo Silva          True
                                                                                  David Silva             True
                                                                                  Ederson                 True
                                                                                  Eric García             True
                                                                                  Fernandinho             True
                                                                                  Gabriel Jesus           True
                                                                                  Ilkay Gündogan          True
                                                                                  John Stones             True
                                                                                  João Cancelo            True
                                                                                  Kevin De Bruyne         True
                                                                                  Kyle Walker             True
                                                                                  Nicolás Otamendi        True
                                                                                  Oleksandr Zinchenko     True
                                                                                  Phil Foden              True
                                                                                  Raheem Sterling         True
                                                                                  Riyad Mahrez            True
                                                                                  Rodri                   True
                                                                                  Scott Carson            True
                                                                  Norwich City    Adam Idah              False
                                                                                  Akin Famewo            False
                                                                                  Archie Mair            False
                                                                                  Ben Godfrey            False
                                                                                  Christoph Zimmerman    False
                                                                                  Daniel Adshead         False
                                                                                  Jamal Lewis            False
                                                                                  Jordan Thomas          False
                                                                                  Josh Martin            False
                                                                                  Kenny McLean           False
                                                                                  Lukas Rupp             False
                                                                                  Marco Stiepermann      False
                                                                                  Mario Vrancic          False
                                                                                  Max Aarons             False
                                                                                  Michael McGovern       False
                                                                                  Onel Hernández         False
                                                                                  Teemu Pukki            False
                                                                                  Tim Krul               False
                                                                                  Todd Cantwell          False

                                                                                                                         position  \
league             season game                                    team            player
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City Aymeric Laporte            Center Left Defender
                                                                                  Benjamin Mendy                       Substitute
                                                                                  Bernardo Silva                       Substitute
                                                                                  David Silva                     Left Midfielder
                                                                                  Ederson                              Goalkeeper
                                                                                  Eric García               Center Right Defender
                                                                                  Fernandinho                          Substitute
                                                                                  Gabriel Jesus                           Forward
                                                                                  Ilkay Gündogan                       Substitute
                                                                                  John Stones                          Substitute
                                                                                  João Cancelo                          Left Back
                                                                                  Kevin De Bruyne                Right Midfielder
                                                                                  Kyle Walker                          Right Back
                                                                                  Nicolás Otamendi                     Substitute
                                                                                  Oleksandr Zinchenko                  Substitute
                                                                                  Phil Foden                         Left Forward
                                                                                  Raheem Sterling                   Right Forward
                                                                                  Riyad Mahrez                         Substitute
                                                                                  Rodri                         Center Midfielder
                                                                                  Scott Carson                         Substitute
                                                                  Norwich City    Adam Idah                            Substitute
                                                                                  Akin Famewo                          Substitute
                                                                                  Archie Mair                          Substitute
                                                                                  Ben Godfrey                Center Left Defender
                                                                                  Christoph Zimmerman       Center Right Defender
                                                                                  Daniel Adshead                       Substitute
                                                                                  Jamal Lewis                           Left Back
                                                                                  Jordan Thomas                        Substitute
                                                                                  Josh Martin                          Substitute
                                                                                  Kenny McLean                    Left Midfielder
                                                                                  Lukas Rupp                     Right Midfielder
                                                                                  Marco Stiepermann          Attacking Midfielder
                                                                                  Mario Vrancic                        Substitute
                                                                                  Max Aarons                           Right Back
                                                                                  Michael McGovern                     Substitute
                                                                                  Onel Hernández        Attacking Midfielder Left
                                                                                  Teemu Pukki                             Forward
                                                                                  Tim Krul                             Goalkeeper
                                                                                  Todd Cantwell        Attacking Midfielder Right

                                                                                                      formation_place  \
league             season game                                    team            player
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City Aymeric Laporte                   6
                                                                                  Benjamin Mendy                    0
                                                                                  Bernardo Silva                    0
                                                                                  David Silva                       8
                                                                                  Ederson                           1
                                                                                  Eric García                       5
                                                                                  Fernandinho                       0
                                                                                  Gabriel Jesus                     9
                                                                                  Ilkay Gündogan                    0
                                                                                  John Stones                       0
                                                                                  João Cancelo                      3
                                                                                  Kevin De Bruyne                   7
                                                                                  Kyle Walker                       2
                                                                                  Nicolás Otamendi                  0
                                                                                  Oleksandr Zinchenko               0
                                                                                  Phil Foden                       11
                                                                                  Raheem Sterling                  10
                                                                                  Riyad Mahrez                      0
                                                                                  Rodri                             4
                                                                                  Scott Carson                      0
                                                                  Norwich City    Adam Idah                         0
                                                                                  Akin Famewo                       0
                                                                                  Archie Mair                       0
                                                                                  Ben Godfrey                       6
                                                                                  Christoph Zimmerman               5
                                                                                  Daniel Adshead                    0
                                                                                  Jamal Lewis                       3
                                                                                  Jordan Thomas                     0
                                                                                  Josh Martin                       0
                                                                                  Kenny McLean                      4
                                                                                  Lukas Rupp                        8
                                                                                  Marco Stiepermann                10
                                                                                  Mario Vrancic                     0
                                                                                  Max Aarons                        2
                                                                                  Michael McGovern                  0
                                                                                  Onel Hernández                   11
                                                                                  Teemu Pukki                       9
                                                                                  Tim Krul                          1
                                                                                  Todd Cantwell                     7

                                                                                                      sub_in  \
league             season game                                    team            player
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City Aymeric Laporte      start
                                                                                  Benjamin Mendy        None
                                                                                  Bernardo Silva          85
                                                                                  David Silva          start
                                                                                  Ederson              start
                                                                                  Eric García          start
                                                                                  Fernandinho             45
                                                                                  Gabriel Jesus        start
                                                                                  Ilkay Gündogan          45
                                                                                  John Stones           None
                                                                                  João Cancelo         start
                                                                                  Kevin De Bruyne      start
                                                                                  Kyle Walker          start
                                                                                  Nicolás Otamendi      None
                                                                                  Oleksandr Zinchenko   None
                                                                                  Phil Foden           start
                                                                                  Raheem Sterling      start
                                                                                  Riyad Mahrez            45
                                                                                  Rodri                start
                                                                                  Scott Carson          None
                                                                  Norwich City    Adam Idah               77
                                                                                  Akin Famewo             92
                                                                                  Archie Mair           None
                                                                                  Ben Godfrey          start
                                                                                  Christoph Zimmerman  start
                                                                                  Daniel Adshead        None
                                                                                  Jamal Lewis          start
                                                                                  Jordan Thomas           92
                                                                                  Josh Martin             87
                                                                                  Kenny McLean         start
                                                                                  Lukas Rupp           start
                                                                                  Marco Stiepermann    start
                                                                                  Mario Vrancic           77
                                                                                  Max Aarons           start
                                                                                  Michael McGovern      None
                                                                                  Onel Hernández       start
                                                                                  Teemu Pukki          start
                                                                                  Tim Krul             start
                                                                                  Todd Cantwell        start

                                                                                                      sub_out  \
league             season game                                    team            player
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City Aymeric Laporte         end
                                                                                  Benjamin Mendy         None
                                                                                  Bernardo Silva          end
                                                                                  David Silva              85
                                                                                  Ederson                 end
                                                                                  Eric García              45

# FBref

In [20]:
fbref = sd.FBref(leagues = "INT-World Cup", seasons = 2018)
print(fbref.__doc__)

[05/29/26 16:58:43] INFO     Saving cached data to C:\Users\raphael.eugenio\soccerdata\data\FBref    ]8;id=973553;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=937156;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

Provides pd.DataFrames from data at http://fbref.com.

Data will be downloaded as necessary and cached locally in
``~/soccerdata/data/FBref``.

Parameters
----------
leagues : string or iterable, optional
    IDs of leagues to include. For efficiently reading data from the Top-5
    European leagues, use "Big 5 European Leagues Combined".
seasons : string, int or list, optional
    Seasons to include. Supports multiple formats.
    Examples: '16-17'; 2016; '2016-17'; [14, 15, 16]
proxy : 'tor' or or dict or list(dict) or callable, optional
    Use a proxy to hide your IP address. Valid options are:
        - "tor": Uses the Tor network. Tor should be running in
          the background on port 9050.
        - str: The address of the proxy server to use.
        - list(str): A list of proxies to choose from. A different proxy will
          be selected from this list after failed requests, allowing rotating
          proxies.
        - callable: A function that returns a valid proxy. This function will
          be called after failed requests, allowing rotating proxies.
no_cache : bool
    If True, will not use cached data.
no_store : bool
    If True, will not store downloaded data.
data_dir : Path
    Path to directory where data will be cached.
path_to_browser : Path, optional
    Path to the Chrome executable.
headless : bool, default: True
    If True, will run Chrome in headless mode. Setting this to False might
    help to avoid getting blocked. Only supported for Selenium <4.13.

*Estatísticas da Temporada da equipe*

In [21]:
team_season_stats = fbref.read_team_season_stats(stat_type = "shooting")
team_season_stats

                                    players_used  90s Standard                 \
                                                           Gls   Sh SoT  SoT%
league        season team
INT-World Cup 2018   Argentina                20  4.0        6   58  17  29.3
                     Australia                15  3.0        2   29   5  17.2
                     Belgium                  21  7.0       15  104  37  35.6
                     Brazil                   18  5.0        8  106  38  35.8
                     Colombia                 20  4.3        6   40  12  30.0
                     Costa Rica               20  3.0        1   26   9  34.6
                     Croatia                  21  8.0       13  114  27  23.7
                     Denmark                  20  4.3        3   40  12  30.0
                     Egypt                    16  3.0        2   29   4  13.8
                     England                  21  7.7       12   88  22  25.0
                     France                   21  7.0       12   79  26  32.9
                     Germany                  20  3.0        2   69  20  29.0
                     IR Iran                  16  3.0        1   22   3  13.6
                     Iceland                  18  3.0        2   33  10  30.3
                     Japan                    18  4.0        6   41  14  34.1
                     Korea Republic           19  3.0        3   33   9  27.3
                     Mexico                   19  4.0        3   60  12  20.0
                     Morocco                  19  3.0        2   35  10  28.6
                     Nigeria                  16  3.0        3   38   8  21.1
                     Panama                   20  3.0        1   24   8  33.3
                     Peru                     17  3.0        2   30  11  36.7
                     Poland                   21  3.0        2   32   8  25.0
                     Portugal                 18  4.0        6   50  12  24.0
                     Russia                   19  5.7       10   49  18  36.7
                     Saudi Arabia             20  3.0        2   35   7  20.0
                     Senegal                  18  3.0        3   33  12  36.4
                     Serbia                   18  3.0        2   34   7  20.6
                     Spain                    17  4.3        6   70  22  31.4
                     Sweden                   19  5.0        5   55  18  32.7
                     Switzerland              17  4.0        5   57  14  24.6
                     Tunisia                  23  3.0        5   34  11  32.4
                     Uruguay                  19  5.0        6   59  20  33.9

                                                                        \
                                     Sh/90 SoT/90  G/Sh G/SoT PK PKatt
league        season team
INT-World Cup 2018   Argentina        14.5   4.25   0.1  0.35  0     1
                     Australia        9.67   1.67   0.0   0.0  2     2
                     Belgium         14.86   5.29  0.13  0.38  1     1
                     Brazil           21.2    7.6  0.08  0.21  0     0
                     Colombia         9.23   2.77  0.15   0.5  0     0
                     Costa Rica       8.67    3.0  0.04  0.11  0     1
                     Croatia         14.25   3.38  0.11  0.44  1     2
                     Denmark          9.23   2.77  0.08  0.25  0     0
                     Egypt            9.67   1.33  0.03  0.25  1     1
                     England         11.48   2.87   0.1  0.41  3     3
                     France          11.29   3.71  0.11  0.35  3     3
                     Germany          23.0   6.67  0.03   0.1  0     0
                     IR Iran          7.33    1.0   0.0   0.0  1     1
                     Iceland          11.0   3.33  0.03   0.1  1     2
                     Japan           10.25    3.5  0.12  0.36  1     1
                     Korea Republic   11.0    3.0  0.09  0.33  0     0
                     Mexico           15.0    3.0  0.03  0.17  1     1
                     Morocco         11.67   3.33  0.06   0.2  0     0
                     Nigeria         12.67   2.67  0.05  0.25  1     1
                     Panama            8.0   2.67  0.04  0.13  0     0
                     Peru             10.0   3.67  0.07  0.18  0     1
                     Poland          10.67   2.67  0.06  0.25  0     0
                     Portugal         12.5    3.0   0.1  0.42  1     2
                     Russia           8.65   3.18  0.18   0.5  1     1
                     Saudi Arabia    11.67   2.33  0.03  0.14  1     2
                     Senegal          11.0    4.0  0.09  0.25  0     0
                     Serbia          11.33   2.33  0.06  0.29  0     0
                     Spain           16.15   5.08  0.09  0.27  0     0
                     Sweden           11.0    3.6  0.05  0.17  2     2
                     Switzerland     14.25    3.5  0.09  0.36  0     0
                     Tunisia         11.33   3.67  0.12  0.36  1     1
                     Uruguay          11.8    4.0   0.1   0.3  0     0

                                                                                   url

league        season team
INT-World Cup 2018   Argentina            /en/squads/f9fddd6e/2018/Argentina-Men-Stats
                     Australia            /en/squads/b90bf4f9/2018/Australia-Men-Stats
                     Belgium                /en/squads/361422b9/2018/Belgium-Men-Stats
                     Brazil                  /en/squads/304635c3/2018/Brazil-Men-Stats
                     Colombia              /en/squads/ab73cfe5/2018/Colombia-Men-Stats
                     Costa Rica          /en/squads/1ea5ab66/2018/Costa-Rica-Men-Stats
                     Croatia                /en/squads/7b08e376/2018/Croatia-Men-Stats
                     Denmark                /en/squads/29a4e4af/2018/Denmark-Men-Stats
                     Egypt                    /en/squads/b8889750/2018/Egypt-Men-Stats
                     England                /en/squads/1862c019/2018/England-Men-Stats
                     France                  /en/squads/b1b36dcd/2018/France-Men-Stats
                     Germany                /en/squads/c1e40422/2018/Germany-Men-Stats
                     IR Iran                /en/squads/6a08f71e/2018/IR-Iran-Men-Stats
                     Iceland                /en/squads/f51a42e5/2018/Iceland-Men-Stats
                     Japan                    /en/squads/ffcf1690/2018/Japan-Men-Stats
                     Korea Republic  /en/squads/473f0fbf/2018/Korea-Republic-Men-Stats
                     Mexico                  /en/squads/b009a548/2018/Mexico-Men-Stats
                     Morocco                /en/squads/af41ccda/2018/Morocco-Men-Stats
                     Nigeria                /en/squads/10abc743/2018/Nigeria-Men-Stats
                     Panama                  /en/squads/6061a82d/2018/Panama-Men-Stats
                     Peru                      /en/squads/f711c854/2018/Peru-Men-Stats
                     Poland                  /en/squads/8912dcf0/2018/Poland-Men-Stats
                     Portugal              /en/squads/4a1b4ea8/2018/Portugal-Men-Stats
                     Russia                  /en/squads/21ced9fe/2018/Russia-Men-Stats
                     Saudi Arabia      /en/squads/6e84edac/2018/Saudi-Arabia-Men-Stats
                     Senegal                /en/squads/9ab5c684/2018/Senegal-Men-Stats
                     Serbia                  /en/squads/1d6f5c9b/2018/Serbia-Men-Stats
                     Spain                    /en/squads/b561dd30/2018/Spain-Men-Stats
                     Sweden                  /en/squads/296f69e7/2018/Sweden-Men-Stats
                     Switzerland        /en/squads/81021a70/2018/Switzerland-Men-Stats
                     Tunisia                /en/squads/a7c7562a/2018/Tunisia-Men-Stats
                     Uruguay                /en/squads/870e020f/2018/Uruguay-Men-Stats

*Estatísticas da partida por equipes*

In [22]:
team_match_stats = fbref.read_team_match_stats(stat_type = "schedule", team = "Brazil")
team_match_stats

                                                              date      time  \
league season team   game
<NA>   2018   Brazil 2015-10-08 Chile-Brazil            2015-10-08  20:30:00
                     2015-10-13 Brazil-Venezuela        2015-10-13  22:00:00
                     2015-11-13 Argentina-Brazil        2015-11-13  21:00:00
                     2015-11-17 Brazil-Peru             2015-11-17  21:00:00
                     2016-03-25 Brazil-Uruguay          2016-03-25  21:45:00
                     2016-03-29 Paraguay-Brazil         2016-03-29  20:45:00
                     2016-09-01 Ecuador-Brazil          2016-09-01  16:00:00
                     2016-09-06 Brazil-Colombia         2016-09-06  20:45:00
                     2016-10-06 Brazil-Bolivia          2016-10-06  21:45:00
                     2016-10-11 Venezuela-Brazil        2016-10-11  20:30:00
                     2016-11-10 Brazil-Argentina        2016-11-10  21:45:00
                     2016-11-15 Peru-Brazil             2016-11-15  21:15:00
                     2017-03-23 Uruguay-Brazil          2017-03-23  20:00:00
                     2017-03-28 Brazil-Paraguay         2017-03-28  21:45:00
                     2017-08-31 Brazil-Ecuador          2017-08-31  21:45:00
                     2017-09-05 Colombia-Brazil         2017-09-05  15:30:00
                     2017-10-05 Bolivia-Brazil          2017-10-05  16:00:00
                     2017-10-10 Brazil-Chile            2017-10-10  20:30:00
                     2018-03-23 Russia-Brazil           2018-03-23  19:00:00
                     2018-03-27 Germany-Brazil          2018-03-27  20:45:00
                     2018-06-03 Brazil-Croatia          2018-06-03  15:00:00
                     2018-06-10 Austria-Brazil          2018-06-10  16:00:00
                     2018-06-17 Switzerland-Switzerland 2018-06-17  21:00:00
                     2018-06-22 Costa Rica-Costa Rica   2018-06-22  15:00:00
                     2018-06-27 Serbia-Serbia           2018-06-27  21:00:00
                     2018-07-02 Mexico-Mexico           2018-07-02  18:00:00
                     2018-07-06 Belgium-Belgium         2018-07-06  21:00:00
                     2018-09-07 United States-Brazil    2018-09-07  19:30:00
                     2018-09-11 Brazil-El Salvador      2018-09-11  20:30:00
                     2018-10-12 Saudi Arabia-Brazil     2018-10-12  21:00:00
                     2018-11-16 Brazil-Uruguay          2018-11-16  20:00:00
                     2018-11-20 Brazil-Cameroon         2018-11-20  19:30:00

                                                                      round  \
league season team   game
<NA>   2018   Brazil 2015-10-08 Chile-Brazil             WCQ — CONMEBOL (M)
                     2015-10-13 Brazil-Venezuela         WCQ — CONMEBOL (M)
                     2015-11-13 Argentina-Brazil         WCQ — CONMEBOL (M)
                     2015-11-17 Brazil-Peru              WCQ — CONMEBOL (M)
                     2016-03-25 Brazil-Uruguay           WCQ — CONMEBOL (M)
                     2016-03-29 Paraguay-Brazil          WCQ — CONMEBOL (M)
                     2016-09-01 Ecuador-Brazil           WCQ — CONMEBOL (M)
                     2016-09-06 Brazil-Colombia          WCQ — CONMEBOL (M)
                     2016-10-06 Brazil-Bolivia           WCQ — CONMEBOL (M)
                     2016-10-11 Venezuela-Brazil         WCQ — CONMEBOL (M)
                     2016-11-10 Brazil-Argentina         WCQ — CONMEBOL (M)
                     2016-11-15 Peru-Brazil              WCQ — CONMEBOL (M)
                     2017-03-23 Uruguay-Brazil           WCQ — CONMEBOL (M)
                     2017-03-28 Brazil-Paraguay          WCQ — CONMEBOL (M)
                     2017-08-31 Brazil-Ecuador           WCQ — CONMEBOL (M)
                     2017-09-05 Colombia-Brazil          WCQ — CONMEBOL (M)
                     2017-10-05 Bolivia-Brazil           WCQ — CONMEBOL (M)
                     2017-10-10 Brazil-Chile             WCQ — CONMEBOL (M)
                     2018-03-23 Russia-Brazil                Friendlies (M)
                     2018-03-27 Germany-Brazil               Friendlies (M)
                     2018-06-03 Brazil-Croatia               Friendlies (M)
                     2018-06-10 Austria-Brazil               Friendlies (M)
                     2018-06-17 Switzerland-Switzerland         Group stage
                     2018-06-22 Costa Rica-Costa Rica           Group stage
                     2018-06-27 Serbia-Serbia                   Group stage
                     2018-07-02 Mexico-Mexico                   Round of 16
                     2018-07-06 Belgium-Belgium              Quarter-finals
                     2018-09-07 United States-Brazil         Friendlies (M)
                     2018-09-11 Brazil-El Salvador           Friendlies (M)
                     2018-10-12 Saudi Arabia-Brazil          Friendlies (M)
                     2018-11-16 Brazil-Uruguay               Friendlies (M)
                     2018-11-20 Brazil-Cameroon              Friendlies (M)

                                                         day    venue result  \
league season team   game
<NA>   2018   Brazil 2015-10-08 Chile-Brazil             Thu     Away      L
                     2015-10-13 Brazil-Venezuela         Tue     Home      W
                     2015-11-13 Argentina-Brazil         Fri     Away      D
                     2015-11-17 Brazil-Peru              Tue     Home      W
                     2016-03-25 Brazil-Uruguay           Fri     Home      D
                     2016-03-29 Paraguay-Brazil          Tue     Away      D
                     2016-09-01 Ecuador-Brazil           Thu     Away      W
                     2016-09-06 Brazil-Colombia          Tue     Home      W
                     2016-10-06 Brazil-Bolivia           Thu     Home      W
                     2016-10-11 Venezuela-Brazil         Tue     Away      W
                     2016-11-10 Brazil-Argentina         Thu     Home      W
                     2016-11-15 Peru-Brazil              Tue     Away      W
                     2017-03-23 Uruguay-Brazil           Thu     Away      W
                     2017-03-28 Brazil-Paraguay          Tue     Home      W
                     2017-08-31 Brazil-Ecuador           Thu     Home      W
                     2017-09-05 Colombia-Brazil          Tue     Away      D
                     2017-10-05 Bolivia-Brazil           Thu     Away      D
                     2017-10-10 Brazil-Chile             Tue     Home      W
                     2018-03-23 Russia-Brazil            Fri     Away      W
                     2018-03-27 Germany-Brazil           Tue     Away      W
                     2018-06-03 Brazil-Croatia           Sun     Home      W
                     2018-06-10 Austria-Brazil           Sun     Away      W
                     2018-06-17 Switzerland-Switzerland  Sun  Neutral      D
                     2018-06-22 Costa Rica-Costa Rica    Fri  Neutral      W
                     2018-06-27 Serbia-Serbia            Wed  Neutral      W
                     2018-07-02 Mexico-Mexico            Mon  Neutral      W
                     2018-07-06 Belgium-Belgium          Fri  Neutral      L
                     2018-09-07 United States-Brazil     Fri     Away      W
                     2018-09-11 Brazil-El Salvador       Tue     Home      W
                     2018-10-12 Saudi Arabia-Brazil      Fri     Away      W
                     2018-11-16 Brazil-Uruguay           Fri     Home      W
                     2018-11-20 Brazil-Cameroon          Tue     Home      W

                                                         GF  GA  \
league season team   game
<NA>   2018   Brazil 2015-10-08 Chile-Brazil              0   2
                     2015-10-13 Brazil-Venezuela          3   1
                     2015-11-13 Argentina-Brazil          1   1
                     2015-11-17 Brazil-Peru               3   0
                     2016-03-25 Brazil-Uruguay            2   2
                     2016-03-29 Paraguay-Brazil           2   2
                     2016-09-01 Ecuador-Brazil            3   0
                     2016-09-06 Brazil-Colombia           2   1
                     2016-10-06 Brazil-Bolivia            5   0
                     2016-10-11 Venezuela-Brazil          2   0
                     2016-11-10 Brazil-Argentina          3   0
                     2016-11-15 Peru-Brazil               2   0
                     2017-03-23 Uruguay-Brazil            4   1
                     2017-03-28 Brazil-Paraguay           3   0
                     2017-08-31 Brazil-Ecuador            2   0
                     2017-09-05 Colombia-Brazil           1   1
                     2017-10-05 Bolivia-Brazil            0   0
                     2017-10-10 Brazil-Chile              3   0
                     2018-03-23 Russia-Brazil             3   0
                     2018-03-27 Germany-Brazil            1   0
                     2018-06-03 Brazil-Croatia            2   0
                     2018-06-10 Austria-Brazil            3   0
                     2018-06-17 Switzerland-Switzerland   1   1
                     2018-06-22 Costa Rica-Costa Rica     2   0
                     2018-06-27 Serbia-Serbia             2   0
                     2018-07-02 Mexico-Mexico             2   0
                     2018-07-06 Belgium-Belgium           1   2
                     2018-09-07 United States-Brazil      2   0
                     2018-09-11 Brazil-El Salvador        5   0
                     2018-10-12 Saudi Arabia-Brazil       2   0
                     2018-11-16 Brazil-Uruguay            1   0
                     2018-11-20 Brazil-Cameroon           1   0

                                                              opponent  Poss  \
league season team   game
<NA>   2018   Brazil 2015-10-08 Chile-Brazil                     Chile  <NA>
                     2015-10-13 Brazil-Venezuela             Venezuela  <NA>
                     2015-11-13 Argentina-Brazil             Argentina  <NA>
                     2015-11-17 Brazil-Peru                       Peru  <NA>
                     2016-03-25 Brazil-Uruguay                 Uruguay  <NA>
                     2016-03-29 Paraguay-Brazil               Paraguay  <NA>
                     2016-09-01 Ecuador-Brazil                 Ecuador  <NA>
                     2016-09-06 Brazil-Colombia               Colombia  <NA>
                     2016-10-06 Brazil-Bolivia                 Bolivia  <NA>
                     2016-10-11 Venezuela-Brazil             Venezuela  <NA>
                     2016-11-10 Brazil-Argentina             Argentina  <NA>
                     2016-11-15 Peru-Brazil                       Peru  <NA>
                     2017-03-23 Uruguay-Brazil                 Uruguay  <NA>
                     2017-03-28 Brazil-Paraguay               Paraguay  <NA>
                     2017-08-31 Brazil-Ecuador                 Ecuador  <NA>
                     2017-09-05 Colombia-Brazil               Colombia  <NA>
                     2017-10-05 Bolivia-Brazil                 Bolivia  <NA>
                     2017-10-10 Brazil-Chile                     Chile  <NA>
                     2018-03-23 Russia-Brazil                   Russia  <NA>
                     2018-03-27 Germany-Brazil                 Germany  <NA>
                     2018-06-03 Brazil-Croatia                 Croatia  <NA>
                     2018-06-10 Austria-Brazil                 Austria  <NA>
                     2018-06-17 Switzerland-Switzerland    Switzerland    55
                     2018-06-22 Costa Rica-Costa Rica       Costa Rica    72
                     2018-06-27 Serbia-Serbia                   Serbia    58
                     2018-07-02 Mexico-Mexico                   Mexico    49
                     2018-07-06 Belgium-Belgium                Belgium    59
                     2018-09-07 United States-Brazil     United States  <NA>
                     2018-09-11 Brazil-El Salvador         El Salvador  <NA>
                     2018-10-12 Saudi Arabia-Brazil       Saudi Arabia  <NA>
                     2018-11-16 Brazil-Uruguay                 Uruguay  <NA>
                     2018-11-20 Brazil-Cameroon               Cameroon  <NA>

                                                         Attendance  \
league season team   game
<NA>   2018   Brazil 2015-10-08 Chile-Brazil                   <NA>
                     2015-10-13 Brazil-Venezuela               <NA>
                     2015-11-13 Argentina-Brazil               <NA>
                     2015-11-17 Brazil-Peru                    <NA>
                     2016-03-25 Brazil-Uruguay                 <NA>
                     2016-03-29 Paraguay-Brazil                <NA>
                     2016-09-01 Ecuador-Brazil                 <NA>
                     2016-09-06 Brazil-Colombia                <NA>
                     2016-10-06 Brazil-Bolivia                30013
                     2016-10-11 Venezuela-Brazil               <NA>
                     2016-11-10 Brazil-Argentina               <NA>
                     2016-11-15 Peru-Brazil                    <NA>
                     2017-03-23 Uruguay-Brazil                 <NA>
                     2017-03-28 Brazil-Paraguay                <NA>
                     2017-08-31 Brazil-Ecuador                 <NA>
                     2017-09-05 Colombia-Brazil                <NA>
                     2017-10-05 Bolivia-Brazil                 <NA>
                     2017-10-10 Brazil-Chile                   <NA>
                     2018-03-23 Russia-Brazil                 59263
                     2018-03-27 Germany-Brazil                72717
                     2018-06-03 Brazil-Croatia                54000
                     2018-06-10 Austria-Brazil                48500
                     2018-06-17 Switzerland-Switzerland       43109
                     2018-06-22 Costa Rica-Costa Rica         64468
                     2018-06-27 Serbia-Serbia                 44190
                     2018-07-02 Mexico-Mexico                 41970
                     2018-07-06 Belgium-Belgium               42873
                     2018-09-07 United States-Brazil          32489
                     2018-09-11 Brazil-El Salvador            28511
                     2018-10-12 Saudi Arabia-Brazil           23401
                     2018-11-16 Brazil-Uruguay                 <NA>
                     2018-11-20 Brazil-Cameroon                <NA>

                                                               Captain  \
league season team   game
<NA>   2018   Brazil 2015-10-08 Chile-Brazil                      <NA>
                     2015-10-13 Brazil-Venezuela                  <NA>
                     2015-11-13 Argentina-Brazil                  <NA>
                     2015-11-17 Brazil-Peru                       <NA>
                     2016-03-25 Brazil-Uruguay                    <NA>
                     2016-03-29 Paraguay-Brazil                   <NA>
                     2016-09-01 Ecuador-Brazil                    <NA>
                     2016-09-06 Brazil-Colombia                   <NA>
                     2016-10-06 Brazil-Bolivia                    <NA>
                     2016-10-11 Venezuela-Brazil                  <NA>
                     2016-11-10 Brazil-Argentina                  <NA>
                     2016-11-15 Peru-Brazil                       <NA>
                     2017-03-23 Uruguay-Brazil                    <NA>
                     2017-03-28 Brazil-Paraguay                   <NA>
                     2017-08-31 Brazil-Ecuador                    <NA>
                     2017-09-05 Colombia-Brazil                   <NA>
                     2017-10-05 Bolivia-Brazil                    <NA>
                     2017-10-10 Brazil-Chile                      <NA>
                     2018-03-23 Russia-Brazil                  Alisson
                     2018-03-27 Germany-Brazil            Thiago Silva
                     2018-06-03 Brazil-Croatia           Gabriel Jesus
                     2018-06-10 Austria-Brazil                 Miranda
                     2018-06-17 Switzerland-Switzerland        Marcelo
                     2018-06-22 Costa Rica-Costa Rica     Thiago Silva
                     2018-06-27 Serbia-Serbia                  Miranda
                     2018-07-02 Mexico-Mexico             Thiago Silva
                     2018-07-06 Belgium-Belgium                Miranda
                     2018-09-07 United States-Brazil            Neymar
                     2018-09-11 Brazil-El Salvador              Neymar
                     2018-10-12 Saudi Arabia-Brazil             Neymar
                     2018-11-16 Brazil-Uruguay                  Neymar
                     2018-11-20 Brazil-Cameroon                 Neymar

                                                        Formation  \
league season team   game
<NA>   2018   Brazil 2015-10-08 Chile-Brazil                 <NA>
                     2015-10-13 Brazil-Venezuela             <NA>
                     2015-11-13 Argentina-Brazil             <NA>
                     2015-11-17 Brazil-Peru                  <NA>
                     2016-03-25 Brazil-Uruguay               <NA>
                     2016-03-29 Paraguay-Brazil              <NA>
                     2016-09-01 Ecuador-Brazil               <NA>
                     2016-09-06 Brazil-Colombia              <NA>
                     2016-10-06 Brazil-Bolivia               <NA>
                     2016-10-11 Venezuela-Brazil             <NA>
                     2016-11-10 Brazil-Argentina             <NA>
                     2016-11-15 Peru-Brazil                  <NA>
                     2017-03-23 Uruguay-Brazil               <NA>
                     2017-03-28 Brazil-Paraguay              <NA>
                     2017-08-31 Brazil-Ecuador               <NA>
                     2017-09-05 Colombia-Brazil              <NA>
                     2017-10-05 Bolivia-Brazil               <NA>
                     2017-10-10 Brazil-Chile                 <NA>
                     2018-03-23 Russia-Brazil               4-3-3
                     2018-03-27 Germany-Brazil              4-3-3
                     2018-06-03 Brazil-Croatia            4-1-4-1
                     2018-06-10 Austria-Brazil            4-1-4-1
                     2018-06-17 Switzerland-Switzerland   4-2-3-1
                     2018-06-22 Costa Rica-Costa Rica     4-2-3-1
                     2018-06-27 Serbia-Serbia             4-2-3-1
                     2018-07-02 Mexico-Mexico             4-2-3-1
                     2018-07-06 Belgium-Belgium           4-2-3-1
                     2018-09-07 United States-Brazil        4-3-3
                     2018-09-11 Brazil-El Salvador          4-3-3
                     2018-10-12 Saudi Arabia-Brazil       4-1-4-1
                     2018-11-16 Brazil-Uruguay              4-3-3
                     2018-11-20 Brazil-Cameroon           4-1-4-1

                                                        Opp Formation  \
league season team   game
<NA>   2018   Brazil 2015-10-08 Chile-Brazil                     <NA>
                     2015-10-13 Brazil-Venezuela                 <NA>
                     2015-11-13 Argentina-Brazil                 <NA>
                     2015-11-17 Brazil-Peru                      <NA>
                     2016-03-25 Brazil-Uruguay                   <NA>
                     2016-03-29 Paraguay-Brazil                  <NA>
                     2016-09-01 Ecuador-Brazil                   <NA>
                     2016-09-06 Brazil-Colombia                  <NA>
                     2016-10-06 Brazil-Bolivia                   <NA>

*Estatísticas da temporada dos jogadores*

In [23]:
player_season_stats = fbref.read_player_season_stats(stat_type = 'standard')
player_season_stats

                                                     nation    pos age  born  \

league        season team      player
INT-World Cup 2018   Argentina Cristian Pavón     Argentina     FW  22  1996
                               Eduardo Salvio     Argentina  MF,DF  27  1990
                               Enzo Pérez         Argentina     MF  32  1986
                               Federico Fazio     Argentina     DF  31  1987
                               Franco Armani      Argentina     GK  31  1986
...                                                     ...    ...  ..   ...
                     Uruguay   Matías Vecino        Uruguay     MF  26  1991
                               Maxi Gómez           Uruguay     FW  21  1996
                               Nahitan Nández       Uruguay     MF  22  1995
                               Rodrigo Bentancur    Uruguay  MF,FW  20  1997
                               Sebastián Coates     Uruguay     DF  27  1990

                                                 Playing Time              \
                                                           MP Starts  Min
league        season team      player
INT-World Cup 2018   Argentina Cristian Pavón               4      1  155
                               Eduardo Salvio               2      2  145
                               Enzo Pérez                   3      3  192
                               Federico Fazio               1      0   45
                               Franco Armani                2      2  180
...                                                       ...    ...  ...
                     Uruguay   Matías Vecino                5      5  414
                               Maxi Gómez                   2      0   33
                               Nahitan Nández               5      4  290
                               Rodrigo Bentancur            5      5  362
                               Sebastián Coates             1      1   90

                                                      Performance      ...  \
                                                  90s         Gls Ast  ...
league        season team      player                                  ...
INT-World Cup 2018   Argentina Cristian Pavón     1.7           0   0  ...
                               Eduardo Salvio     1.6           0   0  ...
                               Enzo Pérez         2.1           0   0  ...
                               Federico Fazio     0.5           0   0  ...
                               Franco Armani      2.0           0   0  ...
...                                               ...         ...  ..  ...
                     Uruguay   Matías Vecino      4.6           0   0  ...
                               Maxi Gómez         0.4           0   0  ...
                               Nahitan Nández     3.2           0   0  ...
                               Rodrigo Bentancur  4.0           0   1  ...
                               Sebastián Coates   1.0           0   0  ...

                                                                          \
                                                 G-PK PK PKatt CrdY CrdR
league        season team      player
INT-World Cup 2018   Argentina Cristian Pavón       0  0     0    0    0
                               Eduardo Salvio       0  0     0    0    0
                               Enzo Pérez           0  0     0    0    0
                               Federico Fazio       0  0     0    0    0
                               Franco Armani        0  0     0    0    0
...                                               ... ..   ...  ...  ...
                     Uruguay   Matías Vecino        0  0     0    0    0
                               Maxi Gómez           0  0     0    0    0
                               Nahitan Nández       0  0     0    0    0
                               Rodrigo Bentancur    0  0     0    2    0
                               Sebastián Coates     0  0     0    0    0

                                                 Per 90 Minutes              \
                                                            Gls   Ast   G+A
league        season team      player
INT-World Cup 2018   Argentina Cristian Pavón               0.0   0.0   0.0
                               Eduardo Salvio               0.0   0.0   0.0
                               Enzo Pérez                   0.0   0.0   0.0
                               Federico Fazio               0.0   0.0   0.0
                               Franco Armani                0.0   0.0   0.0
...                                                         ...   ...   ...
                     Uruguay   Matías Vecino                0.0   0.0   0.0
                               Maxi Gómez                   0.0   0.0   0.0
                               Nahitan Nández               0.0   0.0   0.0
                               Rodrigo Bentancur            0.0  0.25  0.25
                               Sebastián Coates             0.0   0.0   0.0


                                                 G-PK G+A-PK
league        season team      player
INT-World Cup 2018   Argentina Cristian Pavón     0.0    0.0
                               Eduardo Salvio     0.0    0.0
                               Enzo Pérez         0.0    0.0
                               Federico Fazio     0.0    0.0
                               Franco Armani      0.0    0.0
...                                               ...    ...
                     Uruguay   Matías Vecino      0.0    0.0
                               Maxi Gómez         0.0    0.0
                               Nahitan Nández     0.0    0.0
                               Rodrigo Bentancur  0.0   0.25
                               Sebastián Coates   0.0    0.0

[604 rows x 21 columns]

*Calendário de Jogos*

In [24]:
world_games = fbref.read_schedule()
world_games

                                                                 round  week  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia        Group stage     1
                     2018-06-15 Egypt-Uruguay              Group stage     1
                     2018-06-15 Morocco-IR Iran            Group stage     1
                     2018-06-15 Portugal-Spain             Group stage     1
                     2018-06-16 Argentina-Iceland          Group stage     1
...                                                                ...   ...
                     2018-07-07 Sweden-England          Quarter-finals  <NA>
                     2018-07-10 France-Belgium             Semi-finals  <NA>
                     2018-07-11 Croatia-England            Semi-finals  <NA>
                     2018-07-14 Belgium-England      Third-place match  <NA>
                     2018-07-15 France-Croatia                   Final  <NA>

                                                     day       date  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia  Thu 2018-06-14
                     2018-06-15 Egypt-Uruguay        Fri 2018-06-15
                     2018-06-15 Morocco-IR Iran      Fri 2018-06-15
                     2018-06-15 Portugal-Spain       Fri 2018-06-15
                     2018-06-16 Argentina-Iceland    Sat 2018-06-16
...                                                  ...        ...
                     2018-07-07 Sweden-England       Sat 2018-07-07
                     2018-07-10 France-Belgium       Tue 2018-07-10
                     2018-07-11 Croatia-England      Wed 2018-07-11
                     2018-07-14 Belgium-England      Sat 2018-07-14
                     2018-07-15 France-Croatia       Sun 2018-07-15

                                                              time  home_team  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia  18:00 (12:00)     Russia
                     2018-06-15 Egypt-Uruguay        17:00 (09:00)      Egypt
                     2018-06-15 Morocco-IR Iran      18:00 (12:00)    Morocco
                     2018-06-15 Portugal-Spain       21:00 (15:00)   Portugal
                     2018-06-16 Argentina-Iceland    16:00 (10:00)  Argentina
...                                                            ...        ...
                     2018-07-07 Sweden-England       18:00 (11:00)     Sweden
                     2018-07-10 France-Belgium       21:00 (15:00)     France
                     2018-07-11 Croatia-England      21:00 (15:00)    Croatia
                     2018-07-14 Belgium-England      17:00 (11:00)    Belgium
                     2018-07-15 France-Croatia       18:00 (12:00)     France

                                                    score     away_team  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia   5–0  Saudi Arabia
                     2018-06-15 Egypt-Uruguay         0–1       Uruguay
                     2018-06-15 Morocco-IR Iran       0–1       IR Iran
                     2018-06-15 Portugal-Spain        3–3         Spain
                     2018-06-16 Argentina-Iceland     1–1       Iceland
...                                                   ...           ...
                     2018-07-07 Sweden-England        0–2       England
                     2018-07-10 France-Belgium        1–0       Belgium
                     2018-07-11 Croatia-England       2–1       England
                     2018-07-14 Belgium-England       2–0       England
                     2018-07-15 France-Croatia        4–2       Croatia

                                                     attendance  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia       78011
                     2018-06-15 Egypt-Uruguay             27015
                     2018-06-15 Morocco-IR Iran           62548
                     2018-06-15 Portugal-Spain            43866
                     2018-06-16 Argentina-Iceland         44190
...                                                         ...
                     2018-07-07 Sweden-England            39991
                     2018-07-10 France-Belgium            64286
                     2018-07-11 Croatia-England           78011
                     2018-07-14 Belgium-England           64406
                     2018-07-15 France-Croatia            78011

                                                                                           venue  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia  Olimpiyskiy stadion Luzhniki (Neutral Site)
                     2018-06-15 Egypt-Uruguay                 Stadion Central'nyj (Neutral Site)
                     2018-06-15 Morocco-IR Iran                     Gazprom Arena (Neutral Site)
                     2018-06-15 Portugal-Spain          Olimpiyskiy Stadion Fisht (Neutral Site)
                     2018-06-16 Argentina-Iceland                  Otkrytie Arena (Neutral Site)
...                                                                                          ...
                     2018-07-07 Sweden-England                       Cosmos Arena (Neutral Site)
                     2018-07-10 France-Belgium                      Gazprom Arena (Neutral Site)
                     2018-07-11 Croatia-England      Olimpiyskiy stadion Luzhniki (Neutral Site)
                     2018-07-14 Belgium-England                     Gazprom Arena (Neutral Site)
                     2018-07-15 France-Croatia       Olimpiyskiy stadion Luzhniki (Neutral Site)

                                                              referee  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia     Néstor Pitana
                     2018-06-15 Egypt-Uruguay           Björn Kuipers
                     2018-06-15 Morocco-IR Iran          Cüneyt Çakιr
                     2018-06-15 Portugal-Spain        Gianluca Rocchi
                     2018-06-16 Argentina-Iceland    Szymon Marciniak
...                                                               ...
                     2018-07-07 Sweden-England          Björn Kuipers
                     2018-07-10 France-Belgium           Andrés Cunha
                     2018-07-11 Croatia-England          Cüneyt Çakιr
                     2018-07-14 Belgium-England       Alireza Faghani
                     2018-07-15 France-Croatia          Néstor Pitana

                                                                                          match_report  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia  /en/matches/c9d7e48c/Russia-Saudi-Arabia-June-...
                     2018-06-15 Egypt-Uruguay        /en/matches/cea695e1/Egypt-Uruguay-June-15-201...
                     2018-06-15 Morocco-IR Iran      /en/matches/028c7b0f/Morocco-IR-Iran-June-15-2...
                     2018-06-15 Portugal-Spain       /en/matches/2fecb1be/Portugal-Spain-June-15-20...
                     2018-06-16 Argentina-Iceland    /en/matches/1b352279/Argentina-Iceland-June-16...
...                                                                                                ...
                     2018-07-07 Sweden-England       /en/matches/c7b2bf0a/Sweden-England-July-7-201...
                     2018-07-10 France-Belgium       /en/matches/605079c0/France-Belgium-July-10-20...
                     2018-07-11 Croatia-England      /en/matches/12d32bfa/Croatia-England-July-11-2...
                     2018-07-14 Belgium-England      /en/matches/bc417615/Belgium-England-July-14-2...
                     2018-07-15 France-Croatia       /en/matches/a7957cf1/France-Croatia-July-15-20...

                                                                   notes  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia                 <NA>
                     2018-06-15 Egypt-Uruguay                       <NA>
                     2018-06-15 Morocco-IR Iran                     <NA>
                     2018-06-15 Portugal-Spain                      <NA>
                     2018-06-16 Argentina-Iceland                   <NA>
...                                                                  ...
                     2018-07-07 Sweden-England                      <NA>
                     2018-07-10 France-Belgium                      <NA>
                     2018-07-11 Croatia-England      Required Extra Time
                     2018-07-14 Belgium-England                     <NA>
                     2018-07-15 France-Croatia                      <NA>

                                                      game_id
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia  c9d7e48c
                     2018-06-15 Egypt-Uruguay        cea695e1
                     2018-06-15 Morocco-IR Iran      028c7b0f
                     2018-06-15 Portugal-Spain       2fecb1be
                     2018-06-16 Argentina-Iceland    1b352279
...                                                       ...
                     2018-07-07 Sweden-England       c7b2bf0a
                     2018-07-10 France-Belgium       605079c0
                     2018-07-11 Croatia-England      12d32bfa
                     2018-07-14 Belgium-England      bc417615
                     2018-07-15 France-Croatia       a7957cf1

[64 rows x 14 columns]

*Estatísticas das partidas dos jogadores*

In [25]:
player_match_stats = fbref.read_player_match_stats(stat_type = "summary", match_id = "a7957cf1")
player_match_stats

[05/29/26 16:59:13] INFO     [1/1] Retrieving game with id=a7957cf1                                    ]8;id=750550;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=600102;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\fbref.py#765\765]8;;\

                    WARNING  c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\L ]8;id=2994;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=735273;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             ib\site-packages\soccerdata\fbref.py:776: FutureWarning: This
                             search incorrectly ignores the root element, and will be fixed in
                             a future version.  If you rely on the current behaviour, change it
                             to ".//table"
                               html_table = tree.find("//table[@id='" +
                             id_format.format(home_team["id"]) + "']")

                    WARNING  c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\L ]8;id=103662;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=900886;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             ib\site-packages\soccerdata\fbref.py:787: FutureWarning: This
                             search incorrectly ignores the root element, and will be fixed in
                             a future version.  If you rely on the current behaviour, change it
                             to ".//table"
                               html_table = tree.find("//table[@id='" +
                             id_format.format(away_team["id"]) + "']")

                                                                         jersey_number  \

league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić               9
                                                       Ante Rebić                   18
                                                       Danijel Subašić              23
                                                       Dejan Lovren                  6
                                                       Domagoj Vida                 21
                                                       Ivan Perišić                  4
                                                       Ivan Rakitić                  7
                                                       Ivan Strinić                  3
                                                       Luka Modrić                  10
                                                       Marcelo Brozović             11
                                                       Mario Mandžukić              17
                                                       Marko Pjaca                  20
                                                       Šime Vrsaljko                 2
                                               France  Antoine Griezmann             7
                                                       Benjamin Pavard               2
                                                       Blaise Matuidi               14
                                                       Corentin Tolisso             12
                                                       Hugo Lloris                   1
                                                       Kylian Mbappé                10
                                                       Lucas Hernández              21
                                                       N'Golo Kanté                 13
                                                       Nabil Fekir                  18
                                                       Olivier Giroud                9
                                                       Paul Pogba                    6
                                                       Raphaël Varane                4
                                                       Samuel Umtiti                 5
                                                       Steven Nzonzi                15

                                                                            pos  \

league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić    FW,MF
                                                       Ante Rebić            AM
                                                       Danijel Subašić       GK
                                                       Dejan Lovren          CB
                                                       Domagoj Vida          CB
                                                       Ivan Perišić          AM
                                                       Ivan Rakitić          DM
                                                       Ivan Strinić          LB
                                                       Luka Modrić           AM
                                                       Marcelo Brozović      DM
                                                       Mario Mandžukić       FW
                                                       Marko Pjaca        FW,MF
                                                       Šime Vrsaljko         RB
                                               France  Antoine Griezmann     AM
                                                       Benjamin Pavard       RB
                                                       Blaise Matuidi        AM
                                                       Corentin Tolisso   DF,MF
                                                       Hugo Lloris           GK
                                                       Kylian Mbappé         AM
                                                       Lucas Hernández       LB
                                                       N'Golo Kanté          DM
                                                       Nabil Fekir        FW,MF
                                                       Olivier Giroud        FW
                                                       Paul Pogba            DM
                                                       Raphaël Varane        CB
                                                       Samuel Umtiti         CB
                                                       Steven Nzonzi         MF

                                                                             age  \

league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić    27-026
                                                       Ante Rebić         24-297
                                                       Danijel Subašić    33-261
                                                       Dejan Lovren       29-010
                                                       Domagoj Vida       29-077
                                                       Ivan Perišić       29-163
                                                       Ivan Rakitić       30-127
                                                       Ivan Strinić       30-363
                                                       Luka Modrić        32-309
                                                       Marcelo Brozović   25-241
                                                       Mario Mandžukić    32-055
                                                       Marko Pjaca        23-070
                                                       Šime Vrsaljko      26-186
                                               France  Antoine Griezmann  27-116
                                                       Benjamin Pavard    22-109
                                                       Blaise Matuidi     31-097
                                                       Corentin Tolisso   23-346
                                                       Hugo Lloris        31-201
                                                       Kylian Mbappé      19-207
                                                       Lucas Hernández    22-151
                                                       N'Golo Kanté       27-108
                                                       Nabil Fekir        24-362
                                                       Olivier Giroud     31-288
                                                       Paul Pogba         25-122
                                                       Raphaël Varane     25-081
                                                       Samuel Umtiti      24-243
                                                       Steven Nzonzi      29-212

                                                                         min  \

league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić    20
                                                       Ante Rebić         70
                                                       Danijel Subašić    90
                                                       Dejan Lovren       90
                                                       Domagoj Vida       90
                                                       Ivan Perišić       90
                                                       Ivan Rakitić       90
                                                       Ivan Strinić       81
                                                       Luka Modrić        90
                                                       Marcelo Brozović   90
                                                       Mario Mandžukić    90
                                                       Marko Pjaca         9
                                                       Šime Vrsaljko      90
                                               France  Antoine Griezmann  90
                                                       Benjamin Pavard    90
                                                       Blaise Matuidi     72
                                                       Corentin Tolisso   18
                                                       Hugo Lloris        90
                                                       Kylian Mbappé      90
                                                       Lucas Hernández    90
                                                       N'Golo Kanté       53
                                                       Nabil Fekir        10
                                                       Olivier Giroud     80
                                                       Paul Pogba         90
                                                       Raphaël Varane     90
                                                       Samuel Umtiti      90
                                                       Steven Nzonzi      37

                                                                         Performance  \
                                                                                 Gls
league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić             0
                                                       Ante Rebić                  0
                                                       Danijel Subašić             0
                                                       Dejan Lovren                0
                                                       Domagoj Vida                0
                                                       Ivan Perišić                1
                                                       Ivan Rakitić                0
                                                       Ivan Strinić                0
                                                       Luka Modrić                 0
                                                       Marcelo Brozović            0
                                                       Mario Mandžukić             1
                                                       Marko Pjaca                 0
                                                       Šime Vrsaljko               0
                                               France  Antoine Griezmann           1
                                                       Benjamin Pavard             0
                                                       Blaise Matuidi              0
                                                       Corentin Tolisso            0
                                                       Hugo Lloris                 0
                                                       Kylian Mbappé               1
                                                       Lucas Hernández             0
                                                       N'Golo Kanté                0
                                                       Nabil Fekir                 0
                                                       Olivier Giroud              0
                                                       Paul Pogba                  1
                                                       Raphaël Varane              0
                                                       Samuel Umtiti               0
                                                       Steven Nzonzi               0

                                                                              \
                                                                         Ast
league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić     0
                                                       Ante Rebić          0
                                                       Danijel Subašić     0
                                                       Dejan Lovren        0
                                                       Domagoj Vida        1
                                                       Ivan Perišić        0
                                                       Ivan Rakitić        0
                                                       Ivan Strinić        0
                                                       Luka Modrić         0
                                                       Marcelo Brozović    0
                                                       Mario Mandžukić     0
                                                       Marko Pjaca         0
                                                       Šime Vrsaljko       0
                                               France  Antoine Griezmann   0
                                                       Benjamin Pavard     0
                                                       Blaise Matuidi      0
                                                       Corentin Tolisso    0
                                                       Hugo Lloris         0
                                                       Kylian Mbappé       0
                                                       Lucas Hernández     1
                                                       N'Golo Kanté        0
                                                       Nabil Fekir         0
                                                       Olivier Giroud      0
                                                       Paul Pogba          0
                                                       Raphaël Varane      0
                                                       Samuel Umtiti       0
                                                       Steven Nzonzi       0

                                                                             \
                                                                         PK
league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić    0
                                                       Ante Rebić         0
                                                       Danijel Subašić    0
                                                       Dejan Lovren       0
                                                       Domagoj Vida       0
                                                       Ivan Perišić       0
                                                       Ivan Rakitić       0
                                                       Ivan Strinić       0
                                                       Luka Modrić        0
                                                       Marcelo Brozović   0
                                                       Mario Mandžukić    0
                                                       Marko Pjaca        0
                                                       Šime Vrsaljko      0
                                               France  Antoine Griezmann  1
                                                       Benjamin Pavard    0
                                                       Blaise Matuidi     0
                                                       Corentin Tolisso   0
                                                       Hugo Lloris        0
                                                       Kylian Mbappé      0
                                                       Lucas Hernández    0
                                                       N'Golo Kanté       0
                                                       Nabil Fekir        0
                                                       Olivier Giroud     0
                                                       Paul Pogba         0
                                                       Raphaël Varane     0
                                                       Samuel Umtiti      0
                                                       Steven Nzonzi      0

                                                                                \
                                                                         PKatt
league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić       0
                                                       Ante Rebić            0
                                                       Danijel Subašić       0
                                                       Dejan Lovren          0
                                                       Domagoj Vida          0
                                                       Ivan Perišić          0
                                                       Ivan Rakitić          0
                                                       Ivan Strinić          0
                                                       Luka Modrić           0
                                                       Marcelo Brozović      0
                                                       Mario Mandžukić       0
                                                       Marko Pjaca           0
                                                       Šime Vrsaljko         0
                                               France  Antoine Griezmann     1
                                                       Benjamin Pavard       0
                                                       Blaise Matuidi        0
                                                       Corentin Tolisso      0
                                                       Hugo Lloris           0
                                                       Kylian Mbappé         0
                                                       Lucas Hernández       0
                                                       N'Golo Kanté          0
                                                       Nabil Fekir           0
                                                       Olivier Giroud        0
                                                       Paul Pogba            0
                                                       Raphaël Varane        0
                                                       Samuel Umtiti         0
                                                       Steven Nzonzi         0

                                                                             \
                                                                         Sh
league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić    0
                                                       Ante Rebić         3
                                                       Danijel Subašić    0
                                                       Dejan Lovren       1
                                                       Domagoj Vida       2
                                                       Ivan Perišić       2
                                                       Ivan Rakitić       3
                                                       Ivan Strinić       0
                                                       Luka Modrić        0
                                                       Marcelo Brozović   0
                                                       Mario Mandžukić    1
                                                       Marko Pjaca        0

*Formações*

In [26]:
lineups = fbref.read_lineup(match_id = "a7957cf1")
lineups

                    INFO     [1/1] Retrieving game with id=a7957cf1                                    ]8;id=480735;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=727703;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\fbref.py#854\854]8;;\

                    WARNING  c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\L ]8;id=239405;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=77900;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             ib\site-packages\soccerdata\fbref.py:880: FutureWarning: This
                             search incorrectly ignores the root element, and will be fixed in
                             a future version.  If you rely on the current behaviour, change it
                             to ".//table"
                               html_stats_table = tree.find(

[05/29/26 16:59:14] WARNING  c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\L ]8;id=52178;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=583521;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             ib\site-packages\soccerdata\fbref.py:880: FutureWarning: This
                             search incorrectly ignores the root element, and will be fixed in
                             a future version.  If you rely on the current behaviour, change it
                             to ".//table"
                               html_stats_table = tree.find(

                                                jersey_number  \
league        season game
INT-World Cup 2018   2018-07-15 France-Croatia              1
                     2018-07-15 France-Croatia              2
                     2018-07-15 France-Croatia              4
                     2018-07-15 France-Croatia              5
                     2018-07-15 France-Croatia              6
                     2018-07-15 France-Croatia              7
                     2018-07-15 France-Croatia              9
                     2018-07-15 France-Croatia             10
                     2018-07-15 France-Croatia             13
                     2018-07-15 France-Croatia             14
                     2018-07-15 France-Croatia             21
                     2018-07-15 France-Croatia             16
                     2018-07-15 France-Croatia             23
                     2018-07-15 France-Croatia              3
                     2018-07-15 France-Croatia              8
                     2018-07-15 France-Croatia             11
                     2018-07-15 France-Croatia             12
                     2018-07-15 France-Croatia             15
                     2018-07-15 France-Croatia             17
                     2018-07-15 France-Croatia             18
                     2018-07-15 France-Croatia             19
                     2018-07-15 France-Croatia             20
                     2018-07-15 France-Croatia             22
                     2018-07-15 France-Croatia             23
                     2018-07-15 France-Croatia              2
                     2018-07-15 France-Croatia              3
                     2018-07-15 France-Croatia              4
                     2018-07-15 France-Croatia              6
                     2018-07-15 France-Croatia              7
                     2018-07-15 France-Croatia             10
                     2018-07-15 France-Croatia             11
                     2018-07-15 France-Croatia             17
                     2018-07-15 France-Croatia             18
                     2018-07-15 France-Croatia             21
                     2018-07-15 France-Croatia              1
                     2018-07-15 France-Croatia             12
                     2018-07-15 France-Croatia              5
                     2018-07-15 France-Croatia              8
                     2018-07-15 France-Croatia              9
                     2018-07-15 France-Croatia             13
                     2018-07-15 France-Croatia             14
                     2018-07-15 France-Croatia             15
                     2018-07-15 France-Croatia             19
                     2018-07-15 France-Croatia             20
                     2018-07-15 France-Croatia             22

                                                           player     team  \
league        season game
INT-World Cup 2018   2018-07-15 France-Croatia        Hugo Lloris   France
                     2018-07-15 France-Croatia    Benjamin Pavard   France
                     2018-07-15 France-Croatia     Raphaël Varane   France
                     2018-07-15 France-Croatia      Samuel Umtiti   France
                     2018-07-15 France-Croatia         Paul Pogba   France
                     2018-07-15 France-Croatia  Antoine Griezmann   France
                     2018-07-15 France-Croatia     Olivier Giroud   France
                     2018-07-15 France-Croatia      Kylian Mbappé   France
                     2018-07-15 France-Croatia       N'Golo Kanté   France
                     2018-07-15 France-Croatia     Blaise Matuidi   France
                     2018-07-15 France-Croatia    Lucas Hernández   France
                     2018-07-15 France-Croatia     Steve Mandanda   France
                     2018-07-15 France-Croatia    Alphonse Areola   France
                     2018-07-15 France-Croatia   Presnel Kimpembe   France
                     2018-07-15 France-Croatia       Thomas Lemar   France
                     2018-07-15 France-Croatia    Ousmane Dembélé   France
                     2018-07-15 France-Croatia   Corentin Tolisso   France
                     2018-07-15 France-Croatia      Steven Nzonzi   France
                     2018-07-15 France-Croatia          Adil Rami   France
                     2018-07-15 France-Croatia        Nabil Fekir   France
                     2018-07-15 France-Croatia     Djibril Sidibé   France
                     2018-07-15 France-Croatia    Florian Thauvin   France
                     2018-07-15 France-Croatia     Benjamin Mendy   France
                     2018-07-15 France-Croatia    Danijel Subašić  Croatia
                     2018-07-15 France-Croatia      Šime Vrsaljko  Croatia
                     2018-07-15 France-Croatia       Ivan Strinić  Croatia
                     2018-07-15 France-Croatia       Ivan Perišić  Croatia
                     2018-07-15 France-Croatia       Dejan Lovren  Croatia
                     2018-07-15 France-Croatia       Ivan Rakitić  Croatia
                     2018-07-15 France-Croatia        Luka Modrić  Croatia
                     2018-07-15 France-Croatia   Marcelo Brozović  Croatia
                     2018-07-15 France-Croatia    Mario Mandžukić  Croatia
                     2018-07-15 France-Croatia         Ante Rebić  Croatia
                     2018-07-15 France-Croatia       Domagoj Vida  Croatia
                     2018-07-15 France-Croatia  Dominik Livaković  Croatia
                     2018-07-15 France-Croatia      Lovre Kalinić  Croatia
                     2018-07-15 France-Croatia     Vedran Ćorluka  Croatia
                     2018-07-15 France-Croatia      Mateo Kovačić  Croatia
                     2018-07-15 France-Croatia    Andrej Kramarić  Croatia
                     2018-07-15 France-Croatia         Tin Jedvaj  Croatia
                     2018-07-15 France-Croatia     Filip Bradarić  Croatia
                     2018-07-15 France-Croatia    Duje Ćaleta-Car  Croatia
                     2018-07-15 France-Croatia       Milan Badelj  Croatia
                     2018-07-15 France-Croatia        Marko Pjaca  Croatia
                     2018-07-15 France-Croatia      Josip Pivarić  Croatia

                                               is_starter position  \
league        season game
INT-World Cup 2018   2018-07-15 France-Croatia       True       GK
                     2018-07-15 France-Croatia       True       RB
                     2018-07-15 France-Croatia       True       CB
                     2018-07-15 France-Croatia       True       CB
                     2018-07-15 France-Croatia       True       DM
                     2018-07-15 France-Croatia       True       AM
                     2018-07-15 France-Croatia       True       FW
                     2018-07-15 France-Croatia       True       AM
                     2018-07-15 France-Croatia       True       DM
                     2018-07-15 France-Croatia       True       AM
                     2018-07-15 France-Croatia       True       LB
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False    DF,MF
                     2018-07-15 France-Croatia      False       MF
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False    FW,MF
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia       True       GK
                     2018-07-15 France-Croatia       True       RB
                     2018-07-15 France-Croatia       True       LB
                     2018-07-15 France-Croatia       True       AM
                     2018-07-15 France-Croatia       True       CB
                     2018-07-15 France-Croatia       True       DM
                     2018-07-15 France-Croatia       True       AM
                     2018-07-15 France-Croatia       True       DM
                     2018-07-15 France-Croatia       True       FW
                     2018-07-15 France-Croatia       True       AM
                     2018-07-15 France-Croatia       True       CB
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False    FW,MF
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False     <NA>
                     2018-07-15 France-Croatia      False    FW,MF
                     2018-07-15 France-Croatia      False     <NA>

                                                minutes_played
league        season game
INT-World Cup 2018   2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              80
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              53
                     2018-07-15 France-Croatia              72
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia              18
                     2018-07-15 France-Croatia              37
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia              10
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              81
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia              70
                     2018-07-15 France-Croatia              90
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia              20
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               0
                     2018-07-15 France-Croatia               9
                     2018-07-15 France-Croatia               0

*Eventos*

In [27]:
events = fbref.read_events(match_id='a7957cf1')
events

[05/29/26 16:59:52] INFO     [1/1] Retrieving game with id=a7957cf1                                    ]8;id=830677;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=47035;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\fbref.py#949\949]8;;\

                                                   team minute score  \
league        season game
INT-World Cup 2018   2018-07-15 France-Croatia   France    18’   1:0
                     2018-07-15 France-Croatia   France    27’   1:0
                     2018-07-15 France-Croatia  Croatia    28’   1:1
                     2018-07-15 France-Croatia   France    38’   2:1
                     2018-07-15 France-Croatia   France    41’   2:1
                     2018-07-15 France-Croatia   France    54’   2:1
                     2018-07-15 France-Croatia   France    59’   3:1
                     2018-07-15 France-Croatia   France    65’   4:1
                     2018-07-15 France-Croatia  Croatia    69’   4:2
                     2018-07-15 France-Croatia  Croatia    71’   4:2
                     2018-07-15 France-Croatia   France    73’   4:2
                     2018-07-15 France-Croatia   France    81’   4:2
                     2018-07-15 France-Croatia  Croatia    82’   4:2
                     2018-07-15 France-Croatia  Croatia  90+2’   4:2

                                                          player1  \
league        season game
INT-World Cup 2018   2018-07-15 France-Croatia    Mario Mandžukić
                     2018-07-15 France-Croatia       N'Golo Kanté
                     2018-07-15 France-Croatia       Ivan Perišić
                     2018-07-15 France-Croatia  Antoine Griezmann
                     2018-07-15 France-Croatia    Lucas Hernández
                     2018-07-15 France-Croatia      Steven Nzonzi
                     2018-07-15 France-Croatia         Paul Pogba
                     2018-07-15 France-Croatia      Kylian Mbappé
                     2018-07-15 France-Croatia    Mario Mandžukić
                     2018-07-15 France-Croatia    Andrej Kramarić
                     2018-07-15 France-Croatia   Corentin Tolisso
                     2018-07-15 France-Croatia        Nabil Fekir
                     2018-07-15 France-Croatia        Marko Pjaca
                     2018-07-15 France-Croatia      Šime Vrsaljko

                                                        player2     event_type
league        season game
INT-World Cup 2018   2018-07-15 France-Croatia              NaN       own_goal
                     2018-07-15 France-Croatia              NaN    yellow_card
                     2018-07-15 France-Croatia     Domagoj Vida           goal
                     2018-07-15 France-Croatia              NaN   penalty_goal
                     2018-07-15 France-Croatia              NaN    yellow_card
                     2018-07-15 France-Croatia     N'Golo Kanté  substitute_in
                     2018-07-15 France-Croatia              NaN           goal
                     2018-07-15 France-Croatia  Lucas Hernández           goal
                     2018-07-15 France-Croatia              NaN           goal
                     2018-07-15 France-Croatia       Ante Rebić  substitute_in
                     2018-07-15 France-Croatia   Blaise Matuidi  substitute_in
                     2018-07-15 France-Croatia   Olivier Giroud  substitute_in
                     2018-07-15 France-Croatia     Ivan Strinić  substitute_in
                     2018-07-15 France-Croatia              NaN    yellow_card

# Históricos de Partidas

In [33]:
mh = sd.MatchHistory(leagues= "GER-Bundesliga", seasons = 2022)
print(mh.__doc__)

[05/29/26 17:19:26] INFO     Saving cached data to                                                   ]8;id=984770;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=126273;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\
                             C:\Users\raphael.eugenio\soccerdata\data\MatchHistory

Provides pd.DataFrames from CSV files available at http://www.football-data.co.uk/data.php.

Data will be downloaded as necessary and cached locally in
``~/soccerdata/data/MatchHistory``.

Parameters
----------
leagues : string or iterable
    IDs of leagues to include.
seasons : string, int or list
    Seasons to include. Supports multiple formats.
    Examples: '16-17'; 2016; '2016-17'; [14, 15, 16]
proxy : 'tor' or or dict or list(dict) or callable, optional
    Use a proxy to hide your IP address. Valid options are:
        - "tor": Uses the Tor network. Tor should be running in
          the background on port 9050.
        - str: The address of the proxy server to use.
        - list(str): A list of proxies to choose from. A different proxy will
          be selected from this list after failed requests, allowing rotating
          proxies.
        - callable: A function that returns a valid proxy. This function will
          be called after failed requests, allowing rotating proxies.
no_cache : bool
    If True, will not use cached data.
no_store : bool
    If True, will not store downloaded data.
data_dir : Path, optional
    Path to directory where data will be cached.

In [35]:
hist = mh.read_games()
hist.head()

[05/29/26 17:19:36] ERROR    Error while scraping                                                    ]8;id=80000;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=588011;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#527\527]8;;\
                             https://www.football-data.co.uk/mmz4281/2223/D1.csv. Retrying...
                             (attempt 1 of 5).
                             Traceback (most recent call last):
                               File
                             "c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\s
                             ite-packages\soccerdata\_common.py", line 507, in _download_and_save
                                 response.raise_for_status()
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^
                               File
                             "c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\s
                             ite-packages\tls_requests\models\response.py", line 207, in
                             raise_for_status
                                 raise HTTPError(
                                 ...<6 lines>...
                                 )
                             tls_requests.exceptions.HTTPError: 0 TLS Client Error: failed to do
                             request: Get "https://www.football-data.co.uk/mmz4281/2223/D1.csv":
                             tls: failed to verify certificate: x509: certificate signed by unknown
                             authority for url: https://www.football-data.co.uk/mmz4281/2223/D1.csv

                    ERROR    Error while scraping                                                    ]8;id=982245;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=351628;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#527\527]8;;\
                             https://www.football-data.co.uk/mmz4281/2223/D1.csv. Retrying...
                             (attempt 2 of 5).
                             Traceback (most recent call last):
                               File
                             "c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\s
                             ite-packages\soccerdata\_common.py", line 507, in _download_and_save
                                 response.raise_for_status()
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^
                               File
                             "c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\s
                             ite-packages\tls_requests\models\response.py", line 207, in
                             raise_for_status
                                 raise HTTPError(
                                 ...<6 lines>...
                                 )
                             tls_requests.exceptions.HTTPError: 0 TLS Client Error: failed to do
                             request: Get "https://www.football-data.co.uk/mmz4281/2223/D1.csv":
                             tls: failed to verify certificate: x509: certificate signed by unknown
                             authority for url: https://www.football-data.co.uk/mmz4281/2223/D1.csv

                    ERROR    Error while scraping                                                    ]8;id=223626;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=258904;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#527\527]8;;\
                             https://www.football-data.co.uk/mmz4281/2223/D1.csv. Retrying...
                             (attempt 3 of 5).
                             Traceback (most recent call last):
                               File
                             "c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\s
                             ite-packages\soccerdata\_common.py", line 507, in _download_and_save
                                 response.raise_for_status()
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^
                               File
                             "c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\s
                             ite-packages\tls_requests\models\response.py", line 207, in
                             raise_for_status
                                 raise HTTPError(
                                 ...<6 lines>...
                                 )
                             tls_requests.exceptions.HTTPError: 0 TLS Client Error: failed to do
                             request: Get "https://www.football-data.co.uk/mmz4281/2223/D1.csv":
                             tls: failed to verify certificate: x509: certificate signed by unknown
                             authority for url: https://www.football-data.co.uk/mmz4281/2223/D1.csv

                    ERROR    Error while scraping                                                    ]8;id=694984;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=615824;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#527\527]8;;\
                             https://www.football-data.co.uk/mmz4281/2223/D1.csv. Retrying...
                             (attempt 4 of 5).
                             Traceback (most recent call last):
                               File
                             "c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\s
                             ite-packages\soccerdata\_common.py", line 507, in _download_and_save
                                 response.raise_for_status()
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^
                               File
                             "c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\s
                             ite-packages\tls_requests\models\response.py", line 207, in
                             raise_for_status
                                 raise HTTPError(
                                 ...<6 lines>...
                                 )
                             tls_requests.exceptions.HTTPError: 0 TLS Client Error: failed to do
                             request: Get "https://www.football-data.co.uk/mmz4281/2223/D1.csv":
                             tls: failed to verify certificate: x509: certificate signed by unknown
                             authority for url: https://www.football-data.co.uk/mmz4281/2223/D1.csv

                    ERROR    Error while scraping                                                    ]8;id=532434;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=135828;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#527\527]8;;\
                             https://www.football-data.co.uk/mmz4281/2223/D1.csv. Retrying...
                             (attempt 5 of 5).
                             Traceback (most recent call last):
                               File
                             "c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\s
                             ite-packages\soccerdata\_common.py", line 507, in _download_and_save
                                 response.raise_for_status()
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^
                               File
                             "c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\s
                             ite-packages\tls_requests\models\response.py", line 207, in
                             raise_for_status
                                 raise HTTPError(
                                 ...<6 lines>...
                                 )
                             tls_requests.exceptions.HTTPError: 0 TLS Client Error: failed to do
                             request: Get "https://www.football-data.co.uk/mmz4281/2223/D1.csv":
                             tls: failed to verify certificate: x509: certificate signed by unknown
                             authority for url: https://www.football-data.co.uk/mmz4281/2223/D1.csv

ConnectionError: Could not download https://www.football-data.co.uk/mmz4281/2223/D1.csv.

# Sofascore

In [48]:
sofascore = sd.Sofascore(leagues="ESP-La Liga", seasons="2022/2023")
print(sofascore.__doc__)

[05/29/26 17:36:42] INFO     Saving cached data to                                                   ]8;id=895681;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=298562;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\
                             C:\Users\raphael.eugenio\soccerdata\data\Sofascore

Provides pd.DataFrames from data available at http://www.sofascore.com.

Data will be downloaded as necessary and cached locally in
``~/soccerdata/data/Sofascore``.

Parameters
----------
leagues : string or iterable, optional
    IDs of Leagues to include.
seasons : string, int or list, optional
    Seasons to include. Supports multiple formats.
    Examples: '16-17'; 2016; '2016-17'; [14, 15, 16]
proxy : 'tor' or or dict or list(dict) or callable, optional
    Use a proxy to hide your IP address. Valid options are:
        - "tor": Uses the Tor network. Tor should be running in
          the background on port 9050.
        - str: The address of the proxy server to use.
        - list(str): A list of proxies to choose from. A different proxy will
          be selected from this list after failed requests, allowing rotating
          proxies.
        - callable: A function that returns a valid proxy. This function will
          be called after failed requests, allowing rotating proxies.
no_cache : bool
    If True, will not use cached data.
no_store : bool
    If True, will not store downloaded data.
data_dir : Path
    Path to directory where data will be cached.

*Tabela de Classificação*

In [51]:
league_table = sofascore.read_league_table()
league_table.head()

                               team  MP   W  D   L  GF  GA  GD  Pts
league      season
ESP-La Liga 2223       FC Barcelona  38  28  4   6  70  20  50   88
            2223        Real Madrid  38  24  6   8  75  36  39   78
            2223    Atlético Madrid  38  23  8   7  70  33  37   77
            2223      Real Sociedad  38  21  8   9  51  35  16   71
            2223         Villarreal  38  19  7  12  59  40  19   64

*Jogos (Crornogramas)*

In [44]:
schedule = sofascore.read_schedule()
schedule.head()

                                                           round  week  \
league      season game
ESP-La Liga 2223   2022-08-12 Osasuna-Sevilla                  1     1
                   2022-08-13 Celta Vigo-Espanyol              1     1
                   2022-08-13 FC Barcelona-Rayo Vallecano      1     1
                   2022-08-13 Real Valladolid-Villarreal       1     1
                   2022-08-14 Almería-Real Madrid              1     1

                                                                               date  \
league      season game
ESP-La Liga 2223   2022-08-12 Osasuna-Sevilla             2022-08-12 19:00:00+00:00
                   2022-08-13 Celta Vigo-Espanyol         2022-08-13 15:00:00+00:00
                   2022-08-13 FC Barcelona-Rayo Vallecano 2022-08-13 19:00:00+00:00
                   2022-08-13 Real Valladolid-Villarreal  2022-08-13 17:00:00+00:00
                   2022-08-14 Almería-Real Madrid         2022-08-14 20:00:00+00:00

                                                                 home_team  \
league      season game
ESP-La Liga 2223   2022-08-12 Osasuna-Sevilla                      Osasuna
                   2022-08-13 Celta Vigo-Espanyol               Celta Vigo
                   2022-08-13 FC Barcelona-Rayo Vallecano     FC Barcelona
                   2022-08-13 Real Valladolid-Villarreal   Real Valladolid
                   2022-08-14 Almería-Real Madrid                  Almería

                                                                away_team  \
league      season game
ESP-La Liga 2223   2022-08-12 Osasuna-Sevilla                     Sevilla
                   2022-08-13 Celta Vigo-Espanyol                Espanyol
                   2022-08-13 FC Barcelona-Rayo Vallecano  Rayo Vallecano
                   2022-08-13 Real Valladolid-Villarreal       Villarreal
                   2022-08-14 Almería-Real Madrid             Real Madrid

                                                           home_score  \
league      season game
ESP-La Liga 2223   2022-08-12 Osasuna-Sevilla                       2
                   2022-08-13 Celta Vigo-Espanyol                   2
                   2022-08-13 FC Barcelona-Rayo Vallecano           0
                   2022-08-13 Real Valladolid-Villarreal            0
                   2022-08-14 Almería-Real Madrid                   1

                                                           away_score  \
league      season game
ESP-La Liga 2223   2022-08-12 Osasuna-Sevilla                       1
                   2022-08-13 Celta Vigo-Espanyol                   2
                   2022-08-13 FC Barcelona-Rayo Vallecano           0
                   2022-08-13 Real Valladolid-Villarreal            3
                   2022-08-14 Almería-Real Madrid                   2

                                                            game_id
league      season game
ESP-La Liga 2223   2022-08-12 Osasuna-Sevilla              10408559
                   2022-08-13 Celta Vigo-Espanyol          10408645
                   2022-08-13 FC Barcelona-Rayo Vallecano  10408557
                   2022-08-13 Real Valladolid-Villarreal   10408563
                   2022-08-14 Almería-Real Madrid          10408712

# Understat

In [53]:
understat = sd.Understat(leagues = "GER-Bundesliga", seasons = "2024/2025")
print(understat.__doc__)

[05/29/26 17:39:36] INFO     Saving cached data to                                                   ]8;id=64420;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=210417;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\
                             C:\Users\raphael.eugenio\soccerdata\data\Understat

Provides pd.DataFrames from data at https://understat.com.

Data will be downloaded as necessary and cached locally in
``~/soccerdata/data/Understat``.

Parameters
----------
proxy : 'tor' or or dict or list(dict) or callable, optional
    Use a proxy to hide your IP address. Valid options are:
        - "tor": Uses the Tor network. Tor should be running in
          the background on port 9050.
        - str: The address of the proxy server to use.
        - list(str): A list of proxies to choose from. A different proxy will
          be selected from this list after failed requests, allowing rotating
          proxies.
        - callable: A function that returns a valid proxy. This function will
          be called after failed requests, allowing rotating proxies.
no_cache : bool
    If True, will not use cached data.
no_store : bool
    If True, will not store downloaded data.
data_dir : Path
    Path to directory where data will be cached.

*Ligas*

In [54]:
leagues = understat.read_leagues()
leagues.head()

               league_id                                      url
league
GER-Bundesliga         3  https://understat.com/league/Bundesliga

*Temporadas*

In [55]:
seasons = understat.read_seasons()
seasons.head()

,,league_id,season_id,url
league,season,,,
GER-Bundesliga,2425,3,2024,https://understat.com/league/Bundesliga/2024

*Cronograma*

In [56]:
schedule = understat.read_schedule()
schedule.head()

                                                                       league_id  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen          3
                      2024-08-24 Augsburg-Werder Bremen                        3
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt         3
                      2024-08-24 Freiburg-VfB Stuttgart                        3
                      2024-08-24 Hoffenheim-Holstein Kiel                      3

                                                                        season_id  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen        2024
                      2024-08-24 Augsburg-Werder Bremen                      2024
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt       2024
                      2024-08-24 Freiburg-VfB Stuttgart                      2024
                      2024-08-24 Hoffenheim-Holstein Kiel                    2024

                                                                        game_id  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen     27742
                      2024-08-24 Augsburg-Werder Bremen                   27746
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt    27748
                      2024-08-24 Freiburg-VfB Stuttgart                   27745
                      2024-08-24 Hoffenheim-Holstein Kiel                 27744

                                                                                      date  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen  2024-08-23 18:30:00
                      2024-08-24 Augsburg-Werder Bremen                2024-08-24 13:30:00
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt 2024-08-24 16:30:00
                      2024-08-24 Freiburg-VfB Stuttgart                2024-08-24 13:30:00
                      2024-08-24 Hoffenheim-Holstein Kiel              2024-08-24 13:30:00

                                                                        home_team_id  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen            130
                      2024-08-24 Augsburg-Werder Bremen                          121
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt           129
                      2024-08-24 Freiburg-VfB Stuttgart                          135
                      2024-08-24 Hoffenheim-Holstein Kiel                        120

                                                                        away_team_id  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen            119
                      2024-08-24 Augsburg-Werder Bremen                          123
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt           132
                      2024-08-24 Freiburg-VfB Stuttgart                          133
                      2024-08-24 Hoffenheim-Holstein Kiel                        287

                                                                                  home_team  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen   Borussia M.Gladbach
                      2024-08-24 Augsburg-Werder Bremen                            Augsburg
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt    Borussia Dortmund
                      2024-08-24 Freiburg-VfB Stuttgart                            Freiburg
                      2024-08-24 Hoffenheim-Holstein Kiel                        Hoffenheim

                                                                                  away_team  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen      Bayer Leverkusen
                      2024-08-24 Augsburg-Werder Bremen                       Werder Bremen
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt  Eintracht Frankfurt
                      2024-08-24 Freiburg-VfB Stuttgart                       VfB Stuttgart
                      2024-08-24 Hoffenheim-Holstein Kiel                     Holstein Kiel

                                                                       away_team_code  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen             LEV
                      2024-08-24 Augsburg-Werder Bremen                           WER
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt            EIN
                      2024-08-24 Freiburg-VfB Stuttgart                           STU
                      2024-08-24 Hoffenheim-Holstein Kiel                         KIE

                                                                       home_team_code  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen             BMG
                      2024-08-24 Augsburg-Werder Bremen                           AUG
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt            DOR
                      2024-08-24 Freiburg-VfB Stuttgart                           FRE
                      2024-08-24 Hoffenheim-Holstein Kiel                         HOF

                                                                        home_goals  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen            2
                      2024-08-24 Augsburg-Werder Bremen                          2
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt           2
                      2024-08-24 Freiburg-VfB Stuttgart                          3
                      2024-08-24 Hoffenheim-Holstein Kiel                        3

                                                                        away_goals  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen            3
                      2024-08-24 Augsburg-Werder Bremen                          2
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt           0
                      2024-08-24 Freiburg-VfB Stuttgart                          1
                      2024-08-24 Hoffenheim-Holstein Kiel                        2

                                                                        home_xg  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen   1.51665
                      2024-08-24 Augsburg-Werder Bremen                 1.31571
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt   1.9263
                      2024-08-24 Freiburg-VfB Stuttgart                  3.0149
                      2024-08-24 Hoffenheim-Holstein Kiel               3.73706

                                                                         away_xg  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen    3.23588
                      2024-08-24 Augsburg-Werder Bremen                  1.54312
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt   1.15188
                      2024-08-24 Freiburg-VfB Stuttgart                 0.374185
                      2024-08-24 Hoffenheim-Holstein Kiel                1.97238

                                                                        is_result  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen        True
                      2024-08-24 Augsburg-Werder Bremen                      True
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt       True
                      2024-08-24 Freiburg-VfB Stuttgart                      True
                      2024-08-24 Hoffenheim-Holstein Kiel                    True

                                                                        has_data  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen       True
                      2024-08-24 Augsburg-Werder Bremen                     True
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt      True
                      2024-08-24 Freiburg-VfB Stuttgart                     True
                      2024-08-24 Hoffenheim-Holstein Kiel                   True

                                                                                                      url
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen   https://understat.com/match/27742
                      2024-08-24 Augsburg-Werder Bremen                 https://understat.com/match/27746
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt  https://understat.com/match/27748
                      2024-08-24 Freiburg-VfB Stuttgart                 https://understat.com/match/27745
                      2024-08-24 Hoffenheim-Holstein Kiel               https://understat.com/match/27744

*Estatisticas da partidas por equipes*

In [58]:
team_match_stats = understat.read_team_match_stats()
team_match_stats.head()

                                                                       league_id  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen          3
                      2024-08-24 Augsburg-Werder Bremen                        3
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt         3
                      2024-08-24 Freiburg-VfB Stuttgart                        3
                      2024-08-24 Hoffenheim-Holstein Kiel                      3

                                                                        season_id  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen        2024
                      2024-08-24 Augsburg-Werder Bremen                      2024
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt       2024
                      2024-08-24 Freiburg-VfB Stuttgart                      2024
                      2024-08-24 Hoffenheim-Holstein Kiel                    2024

                                                                        game_id  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen     27742
                      2024-08-24 Augsburg-Werder Bremen                   27746
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt    27748
                      2024-08-24 Freiburg-VfB Stuttgart                   27745
                      2024-08-24 Hoffenheim-Holstein Kiel                 27744

                                                                                      date  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen  2024-08-23 18:30:00
                      2024-08-24 Augsburg-Werder Bremen                2024-08-24 13:30:00
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt 2024-08-24 16:30:00
                      2024-08-24 Freiburg-VfB Stuttgart                2024-08-24 13:30:00
                      2024-08-24 Hoffenheim-Holstein Kiel              2024-08-24 13:30:00

                                                                        home_team_id  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen            130
                      2024-08-24 Augsburg-Werder Bremen                          121
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt           129
                      2024-08-24 Freiburg-VfB Stuttgart                          135
                      2024-08-24 Hoffenheim-Holstein Kiel                        120

                                                                        away_team_id  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen            119
                      2024-08-24 Augsburg-Werder Bremen                          123
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt           132
                      2024-08-24 Freiburg-VfB Stuttgart                          133
                      2024-08-24 Hoffenheim-Holstein Kiel                        287

                                                                                  home_team  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen   Borussia M.Gladbach
                      2024-08-24 Augsburg-Werder Bremen                            Augsburg
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt    Borussia Dortmund
                      2024-08-24 Freiburg-VfB Stuttgart                            Freiburg
                      2024-08-24 Hoffenheim-Holstein Kiel                        Hoffenheim

                                                                                  away_team  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen      Bayer Leverkusen
                      2024-08-24 Augsburg-Werder Bremen                       Werder Bremen
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt  Eintracht Frankfurt
                      2024-08-24 Freiburg-VfB Stuttgart                       VfB Stuttgart
                      2024-08-24 Hoffenheim-Holstein Kiel                     Holstein Kiel

                                                                       away_team_code  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen             LEV
                      2024-08-24 Augsburg-Werder Bremen                           WER
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt            EIN
                      2024-08-24 Freiburg-VfB Stuttgart                           STU
                      2024-08-24 Hoffenheim-Holstein Kiel                         KIE

                                                                       home_team_code  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen             BMG
                      2024-08-24 Augsburg-Werder Bremen                           AUG
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt            DOR
                      2024-08-24 Freiburg-VfB Stuttgart                           FRE
                      2024-08-24 Hoffenheim-Holstein Kiel                         HOF

                                                                        ...  \
league         season game                                              ...
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen   ...
                      2024-08-24 Augsburg-Werder Bremen                 ...
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt  ...
                      2024-08-24 Freiburg-VfB Stuttgart                 ...
                      2024-08-24 Hoffenheim-Holstein Kiel               ...

                                                                        away_ppda  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen        18.2
                      2024-08-24 Augsburg-Werder Bremen                 10.789474
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt  34.909091
                      2024-08-24 Freiburg-VfB Stuttgart                 10.111111
                      2024-08-24 Hoffenheim-Holstein Kiel               12.055556

                                                                        away_deep_completions  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen                      10
                      2024-08-24 Augsburg-Werder Bremen                                    11
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt                      6
                      2024-08-24 Freiburg-VfB Stuttgart                                     4
                      2024-08-24 Hoffenheim-Holstein Kiel                                   2

                                                                        home_points  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen             0
                      2024-08-24 Augsburg-Werder Bremen                           1
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt            3
                      2024-08-24 Freiburg-VfB Stuttgart                           3
                      2024-08-24 Hoffenheim-Holstein Kiel                         3

                                                                        home_expected_points  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen                 0.3707
                      2024-08-24 Augsburg-Werder Bremen                                1.193
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt                1.9957
                      2024-08-24 Freiburg-VfB Stuttgart                               2.8978
                      2024-08-24 Hoffenheim-Holstein Kiel                             2.3924

                                                                        home_goals  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen            2
                      2024-08-24 Augsburg-Werder Bremen                          2
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt           2
                      2024-08-24 Freiburg-VfB Stuttgart                          3
                      2024-08-24 Hoffenheim-Holstein Kiel                        3

                                                                        home_xg  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen   1.51665
                      2024-08-24 Augsburg-Werder Bremen                 1.31571
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt   1.9263
                      2024-08-24 Freiburg-VfB Stuttgart                  3.0149
                      2024-08-24 Hoffenheim-Holstein Kiel               3.73706

                                                                        home_np_xg  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen      1.51665
                      2024-08-24 Augsburg-Werder Bremen                    1.31571
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt      1.9263
                      2024-08-24 Freiburg-VfB Stuttgart                     3.0149
                      2024-08-24 Hoffenheim-Holstein Kiel                  2.97928

                                                                        home_np_xg_difference  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen                   -0.79
                      2024-08-24 Augsburg-Werder Bremen                              -0.22741
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt                0.77442
                      2024-08-24 Freiburg-VfB Stuttgart                              2.640715
                      2024-08-24 Hoffenheim-Holstein Kiel                              1.0069

                                                                        home_ppda  \
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen   14.227273
                      2024-08-24 Augsburg-Werder Bremen                     14.75
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt  10.055556
                      2024-08-24 Freiburg-VfB Stuttgart                     34.25
                      2024-08-24 Hoffenheim-Holstein Kiel                   12.95

                                                                        home_deep_completions
league         season game
GER-Bundesliga 2425   2024-08-23 Borussia M.Gladbach-Bayer Leverkusen                       5
                      2024-08-24 Augsburg-Werder Bremen                                     3
                      2024-08-24 Borussia Dortmund-Eintracht Frankfurt                      6
                      2024-08-24 Freiburg-VfB Stuttgart                                     6
                      2024-08-24 Hoffenheim-Holstein Kiel                                  10

[5 rows x 26 columns]

# QuemScoreou

In [78]:
ws = sd.WhoScored(leagues = "ITA-Serie A", seasons = 2021)
print(ws.__doc__)

[05/29/26 18:00:40] INFO     Saving cached data to                                                   ]8;id=469382;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=440865;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\
                             C:\Users\raphael.eugenio\soccerdata\data\WhoScored

[05/29/26 18:00:44] WARNING  c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\L ]8;id=50497;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=319957;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             ib\site-packages\soccerdata\_common.py:144: UserWarning: Season id
                             "2021" is ambiguous: interpreting as "20-21"
                               warnings.warn(msg, stacklevel=1)

Provides pd.DataFrames from data available at http://whoscored.com.

Data will be downloaded as necessary and cached locally in
``~/soccerdata/data/WhoScored``.

Parameters
----------
leagues : string or iterable, optional
    IDs of Leagues to include.
seasons : string, int or list, optional
    Seasons to include. Supports multiple formats.
    Examples: '16-17'; 2016; '2016-17'; [14, 15, 16]
proxy : 'tor' or or dict or list(dict) or callable, optional
    Use a proxy to hide your IP address. Valid options are:
        - "tor": Uses the Tor network. Tor should be running in
          the background on port 9050.
        - str: The address of the proxy server to use.
        - list(str): A list of proxies to choose from. A different proxy will
          be selected from this list after failed requests, allowing rotating
          proxies.
        - callable: A function that returns a valid proxy. This function will
          be called after failed requests, allowing rotating proxies.
no_cache : bool
    If True, will not use cached data.
no_store : bool
    If True, will not store downloaded data.
data_dir : Path
    Path to directory where data will be cached.
path_to_browser : Path, optional
    Path to the Chrome executable.
headless : bool, default: True
    If True, will run Chrome in headless mode. Setting this to False might
    help to avoid getting blocked. Only supported for Selenium <4.13.

In [81]:
epl_schedule = ws.read_matches()
epl_schedule.head()

AttributeError: 'WhoScored' object has no attribute 'read_matches'