In [ ]:
# Importando as Bibliotecas
import soccerdata as sd
import pandas as pd
from pathlib import Path

from soccerdata import ClubElo # As forças relativas da equipe em classificações Elo, na maioria das ligas europeias. Recalculado após cada rodada, inclui histórico.
from soccerdata import ESPN # Resultados históricos, estatísticas e escalações.
from soccerdata import FBref # Resultados históricos, escalações e estatísticas agregadas detalhadas para times e jogadores individuais com base em dados da Opta.
from soccerdata import MatchHistory # Resultados históricos, odds de apostas e estatísticas de partidas. O nível de detalhe depende da liga.
from soccerdata import Sofascore # Resultados, calendários, escalações e estatísticas detalhadas para times e jogadores individuais.
from soccerdata import SoFIFA # Pontuações detalhadas sobre todas as habilidades dos jogadores do EA Sports FC.
from soccerdata import Understat # Estatísticas avançadas como xG, xGBuildup e xGChain, e eventos de arremesso com valores xG associados para as principais ligas europeias.
from soccerdata import WhoScored # Resultados históricos, dados de prévia de partidas e dados detalhados de transmissões de eventos Opta para as grandes ligas.

# Extração de Dados

In [3]:
# Criar instância da classe scraper
fbref = sd.FBref()

[05/29/26 14:37:46] INFO     Saving cached data to C:\Users\raphael.eugenio\soccerdata\data\FBref    ]8;id=473477;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=279339;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

[05/29/26 14:37:52] INFO     No seasons provided. Will retrieve data for the last 5 seasons.         ]8;id=197786;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=598238;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#462\462]8;;\

In [5]:
# Criar Dataframes

season_stats = fbref.read_team_season_stats(stat_type="shooting")

[05/29/26 14:39:18] WARNING  c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\L ]8;id=451597;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=491825;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             ib\site-packages\soccerdata\_common.py:144: UserWarning: Season id
                             "2021" is ambiguous: interpreting as "20-21"
                               warnings.warn(msg, stacklevel=1)

In [11]:
# Criar instância da classe scraper filtrando por ligas e temporadas específicas
fbref = sd.FBref(leagues=["Big 5 European Leagues Combined"], seasons=["2017", "2024"])

# Recuperar dados para as ligas e temporada especificadas
season_stats = fbref.read_team_season_stats(stat_type="shooting")

[05/29/26 14:51:27] INFO     Saving cached data to C:\Users\raphael.eugenio\soccerdata\data\FBref    ]8;id=756571;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=396261;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

In [12]:
sd.FBref.available_leagues()

['Big 5 European Leagues Combined',
 'INT-European Championship',
 "INT-Women's World Cup",
 'INT-World Cup']

In [9]:
# Printa as ligas disponiveis
print(sorted(fbref.available_leagues()))

['Big 5 European Leagues Combined', 'INT-European Championship', "INT-Women's World Cup", 'INT-World Cup']

# Configuração Global

In [26]:
# Definindo caminho
fbref = sd.FBref(
    data_dir=Path(r"C:/Users/raphael.eugenio/Desktop/Raphael/Soccerdata")
)

[05/29/26 15:11:49] INFO     Saving cached data to                                                   ]8;id=909909;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=469402;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\
                             C:\Users\raphael.eugenio\Desktop\Raphael\Soccerdata

[05/29/26 15:11:50] INFO     No seasons provided. Will retrieve data for the last 5 seasons.         ]8;id=116514;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=114599;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#462\462]8;;\

In [28]:
fbref = sd.FBref(
    leagues=["Big 5 European Leagues Combined"],
    seasons=[2024],
    data_dir=Path(r"C:\Users\raphael.eugenio\soccerdata")
)

[05/29/26 15:20:50] INFO     Saving cached data to C:\Users\raphael.eugenio\soccerdata               ]8;id=516315;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=152019;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

# ClubElo

In [ ]:
# Dados do ClubElo, mede por Ranking historico
elo = sd.ClubElo()
print(elo.__doc__)

[05/29/26 15:27:17] INFO     Saving cached data to C:\Users\raphael.eugenio\soccerdata\data\ClubElo  ]8;id=563082;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=321256;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

Provides pd.DataFrames from CSV API at http://api.clubelo.com.

Data will be downloaded as necessary and cached locally in
``~/soccerdata/data/ClubElo``.

Since the source does not provide league names, this class will not filter
by league. League names will be inserted from the other sources where
available. Leagues that are only covered by clubelo.com will have NaN
values.

Parameters
----------
proxy : 'tor' or or dict or list(dict) or callable, optional
    Use a proxy to hide your IP address. Valid options are:
        - "tor": Uses the Tor network. Tor should be running in
          the background on port 9050.
        - str: The address of the proxy server to use.
        - list(str): A list of proxies to choose from. A different proxy will
          be selected from this list after failed requests, allowing rotating
          proxies.
        - callable: A function that returns a valid proxy. This function will
          be called after failed requests, allowing rotating proxies.
no_cache : bool
    If True, will not use cached data.
no_store : bool
    If True, will not store downloaded data.
data_dir : Path
    Path to directory where data will be cached.

In [31]:
current_elo = elo.read_by_date()
current_elo.head()

,rank,country,level,elo,from,to,league
team,,,,,,,
Arsenal,1.0,ENG,1,2065.758057,2026-05-25,2026-05-30,ENG-Premier League
Bayern,2.0,GER,1,2000.870239,2026-05-21,2026-05-31,GER-Bundesliga
Man City,3.0,ENG,1,1969.962524,2026-05-25,2026-05-31,ENG-Premier League
Paris SG,4.0,FRA,1,1964.038452,2026-05-24,2026-05-30,FRA-Ligue 1
Barcelona,5.0,ESP,1,1953.367310,2026-05-24,2026-05-31,ESP-La Liga

In [32]:
barca_elo = elo.read_team_history("Barcelona")
barca_elo.head()

            rank       team country  level          elo         to
from
1939-10-22   NaN  Barcelona     ESP      1  1636.704590 1939-12-03
1939-12-04   NaN  Barcelona     ESP      1  1626.102173 1939-12-10
1939-12-11   NaN  Barcelona     ESP      1  1636.728271 1939-12-17
1939-12-18   NaN  Barcelona     ESP      1  1646.951660 1939-12-24
1939-12-25   NaN  Barcelona     ESP      1  1637.424316 1939-12-31

In [34]:
real_elo = elo.read_team_history("Real Madrid")
real_elo.head()

            rank         team country  level          elo         to
from
1939-10-22   NaN  Real Madrid     ESP      1  1636.704590 1939-12-03
1939-12-04   NaN  Real Madrid     ESP      1  1621.710571 1939-12-10
1939-12-11   NaN  Real Madrid     ESP      1  1616.419678 1939-12-17
1939-12-18   NaN  Real Madrid     ESP      1  1625.154663 1939-12-24
1939-12-25   NaN  Real Madrid     ESP      1  1635.314575 1939-12-31

# ESPN

In [ ]:
# Definindo Liga e Temporada
espn = sd.ESPN(leagues = "ENG-Premier League", seasons=2021)
print(espn.__doc__)

*Calendário de Jogos*

In [44]:
# Calendário da temporada inteira
epl_schedule = espn.read_schedule()
epl_schedule

                                                                                           date  \
league             season game
ENG-Premier League 2021   2019-08-09 Liverpool-Norwich City           2019-08-09 19:00:00+00:00
                          2019-08-10 AFC Bournemouth-Sheffield United 2019-08-10 14:00:00+00:00
                          2019-08-10 Burnley-Southampton              2019-08-10 14:00:00+00:00
                          2019-08-10 Crystal Palace-Everton           2019-08-10 14:00:00+00:00
                          2019-08-10 Tottenham Hotspur-Aston Villa    2019-08-10 16:30:00+00:00
...                                                                                         ...
                          2020-07-26 Leicester City-Manchester United 2020-07-26 15:00:00+00:00
                          2020-07-26 Manchester City-Norwich City     2020-07-26 15:00:00+00:00
                          2020-07-26 Newcastle United-Liverpool       2020-07-26 15:00:00+00:00
                          2020-07-26 Southampton-Sheffield United     2020-07-26 15:00:00+00:00
                          2020-07-26 West Ham United-Aston Villa      2020-07-26 15:00:00+00:00

                                                                               home_team  \
league             season game
ENG-Premier League 2021   2019-08-09 Liverpool-Norwich City                    Liverpool
                          2019-08-10 AFC Bournemouth-Sheffield United    AFC Bournemouth
                          2019-08-10 Burnley-Southampton                         Burnley
                          2019-08-10 Crystal Palace-Everton               Crystal Palace
                          2019-08-10 Tottenham Hotspur-Aston Villa     Tottenham Hotspur
...                                                                                  ...
                          2020-07-26 Leicester City-Manchester United     Leicester City
                          2020-07-26 Manchester City-Norwich City        Manchester City
                          2020-07-26 Newcastle United-Liverpool         Newcastle United
                          2020-07-26 Southampton-Sheffield United            Southampton
                          2020-07-26 West Ham United-Aston Villa         West Ham United

                                                                               away_team  \
league             season game
ENG-Premier League 2021   2019-08-09 Liverpool-Norwich City                 Norwich City
                          2019-08-10 AFC Bournemouth-Sheffield United   Sheffield United
                          2019-08-10 Burnley-Southampton                     Southampton
                          2019-08-10 Crystal Palace-Everton                      Everton
                          2019-08-10 Tottenham Hotspur-Aston Villa           Aston Villa
...                                                                                  ...
                          2020-07-26 Leicester City-Manchester United  Manchester United
                          2020-07-26 Manchester City-Norwich City           Norwich City
                          2020-07-26 Newcastle United-Liverpool                Liverpool
                          2020-07-26 Southampton-Sheffield United       Sheffield United
                          2020-07-26 West Ham United-Aston Villa             Aston Villa

                                                                       game_id  \
league             season game
ENG-Premier League 2021   2019-08-09 Liverpool-Norwich City             541844
                          2019-08-10 AFC Bournemouth-Sheffield United   541840
                          2019-08-10 Burnley-Southampton                541841
                          2019-08-10 Crystal Palace-Everton             541839
                          2019-08-10 Tottenham Hotspur-Aston Villa      541837
...                                                                        ...
                          2020-07-26 Leicester City-Manchester United   541469
                          2020-07-26 Manchester City-Norwich City       541470
                          2020-07-26 Newcastle United-Liverpool         541468
                          2020-07-26 Southampton-Sheffield United       541471
                          2020-07-26 West Ham United-Aston Villa        541465

                                                                      league_id
league             season game
ENG-Premier League 2021   2019-08-09 Liverpool-Norwich City               eng.1
                          2019-08-10 AFC Bournemouth-Sheffield United     eng.1
                          2019-08-10 Burnley-Southampton                  eng.1
                          2019-08-10 Crystal Palace-Everton               eng.1
                          2019-08-10 Tottenham Hotspur-Aston Villa        eng.1
...                                                                         ...
                          2020-07-26 Leicester City-Manchester United     eng.1
                          2020-07-26 Manchester City-Norwich City         eng.1
                          2020-07-26 Newcastle United-Liverpool           eng.1
                          2020-07-26 Southampton-Sheffield United         eng.1
                          2020-07-26 West Ham United-Aston Villa          eng.1

[380 rows x 5 columns]

*Estatísticas do jogo*

In [ ]:
# Estatisticas dos jogos por partida selecionando por id
matchsheet = espn.read_matchsheet(match_id=541470)
matchsheet.head()

                                                                                   is_home  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City     True
                                                                  Norwich City       False

                                                                                            venue  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City  Etihad Stadium
                                                                  Norwich City     Etihad Stadium

                                                                                   attendance  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City           0
                                                                  Norwich City              0

                                                                                  capacity  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City     None
                                                                  Norwich City        None

                                                                                                                              roster  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City  [{'active': True, 'starter': True, 'jersey': '...
                                                                  Norwich City     [{'active': True, 'starter': True, 'jersey': '...

                                                                                  fouls_committed  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City               7
                                                                  Norwich City                  4

                                                                                  yellow_cards  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City            1
                                                                  Norwich City               1

                                                                                  red_cards  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City         0
                                                                  Norwich City            0

                                                                                  offsides  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City        0
                                                                  Norwich City           2

                                                                                  won_corners  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City           9
                                                                  Norwich City              0

                                                                                   ...  \
league             season game                                    team             ...
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City  ...
                                                                  Norwich City     ...

                                                                                  total_long_balls  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City               45
                                                                  Norwich City                  63

                                                                                  accurate_long_balls  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City                  35
                                                                  Norwich City                     26

                                                                                  longball_pct  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City          0.8
                                                                  Norwich City             0.4

                                                                                  blocked_shots  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City             9
                                                                  Norwich City                0

                                                                                  effective_tackles  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City                 8
                                                                  Norwich City                    5

                                                                                  total_tackles  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City            12
                                                                  Norwich City               14

                                                                                  tackle_pct  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City        0.7
                                                                  Norwich City           0.4

                                                                                  interceptions  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City            10
                                                                  Norwich City               14

                                                                                  effective_clearance  \
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City                   5
                                                                  Norwich City                     26

                                                                                  total_clearance
league             season game                                    team
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City               5
                                                                  Norwich City                 26

[2 rows x 33 columns]

*Formações de Jogo*

In [47]:
# Formação de Jogo por ID
lineups = espn.read_lineup(match_id=541470)
lineups

                                                                                                       is_home  \
league             season game                                    team            player
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City Aymeric Laporte         True
                                                                                  Benjamin Mendy          True
                                                                                  Bernardo Silva          True
                                                                                  David Silva             True
                                                                                  Ederson                 True
                                                                                  Eric García             True
                                                                                  Fernandinho             True
                                                                                  Gabriel Jesus           True
                                                                                  Ilkay Gündogan          True
                                                                                  John Stones             True
                                                                                  João Cancelo            True
                                                                                  Kevin De Bruyne         True
                                                                                  Kyle Walker             True
                                                                                  Nicolás Otamendi        True
                                                                                  Oleksandr Zinchenko     True
                                                                                  Phil Foden              True
                                                                                  Raheem Sterling         True
                                                                                  Riyad Mahrez            True
                                                                                  Rodri                   True
                                                                                  Scott Carson            True
                                                                  Norwich City    Adam Idah              False
                                                                                  Akin Famewo            False
                                                                                  Archie Mair            False
                                                                                  Ben Godfrey            False
                                                                                  Christoph Zimmerman    False
                                                                                  Daniel Adshead         False
                                                                                  Jamal Lewis            False
                                                                                  Jordan Thomas          False
                                                                                  Josh Martin            False
                                                                                  Kenny McLean           False
                                                                                  Lukas Rupp             False
                                                                                  Marco Stiepermann      False
                                                                                  Mario Vrancic          False
                                                                                  Max Aarons             False
                                                                                  Michael McGovern       False
                                                                                  Onel Hernández         False
                                                                                  Teemu Pukki            False
                                                                                  Tim Krul               False
                                                                                  Todd Cantwell          False

                                                                                                                         position  \
league             season game                                    team            player
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City Aymeric Laporte            Center Left Defender
                                                                                  Benjamin Mendy                       Substitute
                                                                                  Bernardo Silva                       Substitute
                                                                                  David Silva                     Left Midfielder
                                                                                  Ederson                              Goalkeeper
                                                                                  Eric García               Center Right Defender
                                                                                  Fernandinho                          Substitute
                                                                                  Gabriel Jesus                           Forward
                                                                                  Ilkay Gündogan                       Substitute
                                                                                  John Stones                          Substitute
                                                                                  João Cancelo                          Left Back
                                                                                  Kevin De Bruyne                Right Midfielder
                                                                                  Kyle Walker                          Right Back
                                                                                  Nicolás Otamendi                     Substitute
                                                                                  Oleksandr Zinchenko                  Substitute
                                                                                  Phil Foden                         Left Forward
                                                                                  Raheem Sterling                   Right Forward
                                                                                  Riyad Mahrez                         Substitute
                                                                                  Rodri                         Center Midfielder
                                                                                  Scott Carson                         Substitute
                                                                  Norwich City    Adam Idah                            Substitute
                                                                                  Akin Famewo                          Substitute
                                                                                  Archie Mair                          Substitute
                                                                                  Ben Godfrey                Center Left Defender
                                                                                  Christoph Zimmerman       Center Right Defender
                                                                                  Daniel Adshead                       Substitute
                                                                                  Jamal Lewis                           Left Back
                                                                                  Jordan Thomas                        Substitute
                                                                                  Josh Martin                          Substitute
                                                                                  Kenny McLean                    Left Midfielder
                                                                                  Lukas Rupp                     Right Midfielder
                                                                                  Marco Stiepermann          Attacking Midfielder
                                                                                  Mario Vrancic                        Substitute
                                                                                  Max Aarons                           Right Back
                                                                                  Michael McGovern                     Substitute
                                                                                  Onel Hernández        Attacking Midfielder Left
                                                                                  Teemu Pukki                             Forward
                                                                                  Tim Krul                             Goalkeeper
                                                                                  Todd Cantwell        Attacking Midfielder Right

                                                                                                      formation_place  \
league             season game                                    team            player
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City Aymeric Laporte                   6
                                                                                  Benjamin Mendy                    0
                                                                                  Bernardo Silva                    0
                                                                                  David Silva                       8
                                                                                  Ederson                           1
                                                                                  Eric García                       5
                                                                                  Fernandinho                       0
                                                                                  Gabriel Jesus                     9
                                                                                  Ilkay Gündogan                    0
                                                                                  John Stones                       0
                                                                                  João Cancelo                      3
                                                                                  Kevin De Bruyne                   7
                                                                                  Kyle Walker                       2
                                                                                  Nicolás Otamendi                  0
                                                                                  Oleksandr Zinchenko               0
                                                                                  Phil Foden                       11
                                                                                  Raheem Sterling                  10
                                                                                  Riyad Mahrez                      0
                                                                                  Rodri                             4
                                                                                  Scott Carson                      0
                                                                  Norwich City    Adam Idah                         0
                                                                                  Akin Famewo                       0
                                                                                  Archie Mair                       0
                                                                                  Ben Godfrey                       6
                                                                                  Christoph Zimmerman               5
                                                                                  Daniel Adshead                    0
                                                                                  Jamal Lewis                       3
                                                                                  Jordan Thomas                     0
                                                                                  Josh Martin                       0
                                                                                  Kenny McLean                      4
                                                                                  Lukas Rupp                        8
                                                                                  Marco Stiepermann                10
                                                                                  Mario Vrancic                     0
                                                                                  Max Aarons                        2
                                                                                  Michael McGovern                  0
                                                                                  Onel Hernández                   11
                                                                                  Teemu Pukki                       9
                                                                                  Tim Krul                          1
                                                                                  Todd Cantwell                     7

                                                                                                      sub_in  \
league             season game                                    team            player
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City Aymeric Laporte      start
                                                                                  Benjamin Mendy        None
                                                                                  Bernardo Silva          85
                                                                                  David Silva          start
                                                                                  Ederson              start
                                                                                  Eric García          start
                                                                                  Fernandinho             45
                                                                                  Gabriel Jesus        start
                                                                                  Ilkay Gündogan          45
                                                                                  John Stones           None
                                                                                  João Cancelo         start
                                                                                  Kevin De Bruyne      start
                                                                                  Kyle Walker          start
                                                                                  Nicolás Otamendi      None
                                                                                  Oleksandr Zinchenko   None
                                                                                  Phil Foden           start
                                                                                  Raheem Sterling      start
                                                                                  Riyad Mahrez            45
                                                                                  Rodri                start
                                                                                  Scott Carson          None
                                                                  Norwich City    Adam Idah               77
                                                                                  Akin Famewo             92
                                                                                  Archie Mair           None
                                                                                  Ben Godfrey          start
                                                                                  Christoph Zimmerman  start
                                                                                  Daniel Adshead        None
                                                                                  Jamal Lewis          start
                                                                                  Jordan Thomas           92
                                                                                  Josh Martin             87
                                                                                  Kenny McLean         start
                                                                                  Lukas Rupp           start
                                                                                  Marco Stiepermann    start
                                                                                  Mario Vrancic           77
                                                                                  Max Aarons           start
                                                                                  Michael McGovern      None
                                                                                  Onel Hernández       start
                                                                                  Teemu Pukki          start
                                                                                  Tim Krul             start
                                                                                  Todd Cantwell        start

                                                                                                      sub_out  \
league             season game                                    team            player
ENG-Premier League 2021   2020-07-26 Manchester City-Norwich City Manchester City Aymeric Laporte         end
                                                                                  Benjamin Mendy         None
                                                                                  Bernardo Silva          end
                                                                                  David Silva              85
                                                                                  Ederson                 end
                                                                                  Eric García              45

# FBref

In [ ]:
fbref = sd.FBref(leagues = "INT-World Cup", seasons = 2018)
print(fbref.__doc__)

ValueError:
                        Invalid league 'ENG-Premier League'. Valid leagues are:
                        ['Big 5 European Leagues Combined',
 'INT-European Championship',
 "INT-Women's World Cup",
 'INT-World Cup']

*Estatísticas da Temporada da equipe*

In [ ]:
team_season_stats = fbref.read_team_season_stats(stat_type = "shooting")
team_season_stats

*Estatísticas da partida por equipes*

In [ ]:
team_match_stats = fbref.read_team_match_stats(stat_type = "schedule", team = "Brazil")
team_match_stats

*Estatísticas da temporada dos jogadores*

In [58]:
player_season_stats = fbref.read_player_season_stats(stat_type = 'standard')
player_season_stats

                                                     nation    pos age  born  \

league        season team      player
INT-World Cup 2018   Argentina Cristian Pavón     Argentina     FW  22  1996
                               Eduardo Salvio     Argentina  MF,DF  27  1990
                               Enzo Pérez         Argentina     MF  32  1986
                               Federico Fazio     Argentina     DF  31  1987
                               Franco Armani      Argentina     GK  31  1986
...                                                     ...    ...  ..   ...
                     Uruguay   Matías Vecino        Uruguay     MF  26  1991
                               Maxi Gómez           Uruguay     FW  21  1996
                               Nahitan Nández       Uruguay     MF  22  1995
                               Rodrigo Bentancur    Uruguay  MF,FW  20  1997
                               Sebastián Coates     Uruguay     DF  27  1990

                                                 Playing Time              \
                                                           MP Starts  Min
league        season team      player
INT-World Cup 2018   Argentina Cristian Pavón               4      1  155
                               Eduardo Salvio               2      2  145
                               Enzo Pérez                   3      3  192
                               Federico Fazio               1      0   45
                               Franco Armani                2      2  180
...                                                       ...    ...  ...
                     Uruguay   Matías Vecino                5      5  414
                               Maxi Gómez                   2      0   33
                               Nahitan Nández               5      4  290
                               Rodrigo Bentancur            5      5  362
                               Sebastián Coates             1      1   90

                                                      Performance      ...  \
                                                  90s         Gls Ast  ...
league        season team      player                                  ...
INT-World Cup 2018   Argentina Cristian Pavón     1.7           0   0  ...
                               Eduardo Salvio     1.6           0   0  ...
                               Enzo Pérez         2.1           0   0  ...
                               Federico Fazio     0.5           0   0  ...
                               Franco Armani      2.0           0   0  ...
...                                               ...         ...  ..  ...
                     Uruguay   Matías Vecino      4.6           0   0  ...
                               Maxi Gómez         0.4           0   0  ...
                               Nahitan Nández     3.2           0   0  ...
                               Rodrigo Bentancur  4.0           0   1  ...
                               Sebastián Coates   1.0           0   0  ...

                                                                          \
                                                 G-PK PK PKatt CrdY CrdR
league        season team      player
INT-World Cup 2018   Argentina Cristian Pavón       0  0     0    0    0
                               Eduardo Salvio       0  0     0    0    0
                               Enzo Pérez           0  0     0    0    0
                               Federico Fazio       0  0     0    0    0
                               Franco Armani        0  0     0    0    0
...                                               ... ..   ...  ...  ...
                     Uruguay   Matías Vecino        0  0     0    0    0
                               Maxi Gómez           0  0     0    0    0
                               Nahitan Nández       0  0     0    0    0
                               Rodrigo Bentancur    0  0     0    2    0
                               Sebastián Coates     0  0     0    0    0

                                                 Per 90 Minutes              \
                                                            Gls   Ast   G+A
league        season team      player
INT-World Cup 2018   Argentina Cristian Pavón               0.0   0.0   0.0
                               Eduardo Salvio               0.0   0.0   0.0
                               Enzo Pérez                   0.0   0.0   0.0
                               Federico Fazio               0.0   0.0   0.0
                               Franco Armani                0.0   0.0   0.0
...                                                         ...   ...   ...
                     Uruguay   Matías Vecino                0.0   0.0   0.0
                               Maxi Gómez                   0.0   0.0   0.0
                               Nahitan Nández               0.0   0.0   0.0
                               Rodrigo Bentancur            0.0  0.25  0.25
                               Sebastián Coates             0.0   0.0   0.0


                                                 G-PK G+A-PK
league        season team      player
INT-World Cup 2018   Argentina Cristian Pavón     0.0    0.0
                               Eduardo Salvio     0.0    0.0
                               Enzo Pérez         0.0    0.0
                               Federico Fazio     0.0    0.0
                               Franco Armani      0.0    0.0
...                                               ...    ...
                     Uruguay   Matías Vecino      0.0    0.0
                               Maxi Gómez         0.0    0.0
                               Nahitan Nández     0.0    0.0
                               Rodrigo Bentancur  0.0   0.25
                               Sebastián Coates   0.0    0.0

[604 rows x 21 columns]

*Calendário de Jogos*

In [59]:
world_games = fbref.read_schedule()
world_games

                                                                 round  week  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia        Group stage     1
                     2018-06-15 Egypt-Uruguay              Group stage     1
                     2018-06-15 Morocco-IR Iran            Group stage     1
                     2018-06-15 Portugal-Spain             Group stage     1
                     2018-06-16 Argentina-Iceland          Group stage     1
...                                                                ...   ...
                     2018-07-07 Sweden-England          Quarter-finals  <NA>
                     2018-07-10 France-Belgium             Semi-finals  <NA>
                     2018-07-11 Croatia-England            Semi-finals  <NA>
                     2018-07-14 Belgium-England      Third-place match  <NA>
                     2018-07-15 France-Croatia                   Final  <NA>

                                                     day       date  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia  Thu 2018-06-14
                     2018-06-15 Egypt-Uruguay        Fri 2018-06-15
                     2018-06-15 Morocco-IR Iran      Fri 2018-06-15
                     2018-06-15 Portugal-Spain       Fri 2018-06-15
                     2018-06-16 Argentina-Iceland    Sat 2018-06-16
...                                                  ...        ...
                     2018-07-07 Sweden-England       Sat 2018-07-07
                     2018-07-10 France-Belgium       Tue 2018-07-10
                     2018-07-11 Croatia-England      Wed 2018-07-11
                     2018-07-14 Belgium-England      Sat 2018-07-14
                     2018-07-15 France-Croatia       Sun 2018-07-15

                                                              time  home_team  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia  18:00 (12:00)     Russia
                     2018-06-15 Egypt-Uruguay        17:00 (09:00)      Egypt
                     2018-06-15 Morocco-IR Iran      18:00 (12:00)    Morocco
                     2018-06-15 Portugal-Spain       21:00 (15:00)   Portugal
                     2018-06-16 Argentina-Iceland    16:00 (10:00)  Argentina
...                                                            ...        ...
                     2018-07-07 Sweden-England       18:00 (11:00)     Sweden
                     2018-07-10 France-Belgium       21:00 (15:00)     France
                     2018-07-11 Croatia-England      21:00 (15:00)    Croatia
                     2018-07-14 Belgium-England      17:00 (11:00)    Belgium
                     2018-07-15 France-Croatia       18:00 (12:00)     France

                                                    score     away_team  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia   5–0  Saudi Arabia
                     2018-06-15 Egypt-Uruguay         0–1       Uruguay
                     2018-06-15 Morocco-IR Iran       0–1       IR Iran
                     2018-06-15 Portugal-Spain        3–3         Spain
                     2018-06-16 Argentina-Iceland     1–1       Iceland
...                                                   ...           ...
                     2018-07-07 Sweden-England        0–2       England
                     2018-07-10 France-Belgium        1–0       Belgium
                     2018-07-11 Croatia-England       2–1       England
                     2018-07-14 Belgium-England       2–0       England
                     2018-07-15 France-Croatia        4–2       Croatia

                                                     attendance  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia       78011
                     2018-06-15 Egypt-Uruguay             27015
                     2018-06-15 Morocco-IR Iran           62548
                     2018-06-15 Portugal-Spain            43866
                     2018-06-16 Argentina-Iceland         44190
...                                                         ...
                     2018-07-07 Sweden-England            39991
                     2018-07-10 France-Belgium            64286
                     2018-07-11 Croatia-England           78011
                     2018-07-14 Belgium-England           64406
                     2018-07-15 France-Croatia            78011

                                                                                           venue  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia  Olimpiyskiy stadion Luzhniki (Neutral Site)
                     2018-06-15 Egypt-Uruguay                 Stadion Central'nyj (Neutral Site)
                     2018-06-15 Morocco-IR Iran                     Gazprom Arena (Neutral Site)
                     2018-06-15 Portugal-Spain          Olimpiyskiy Stadion Fisht (Neutral Site)
                     2018-06-16 Argentina-Iceland                  Otkrytie Arena (Neutral Site)
...                                                                                          ...
                     2018-07-07 Sweden-England                       Cosmos Arena (Neutral Site)
                     2018-07-10 France-Belgium                      Gazprom Arena (Neutral Site)
                     2018-07-11 Croatia-England      Olimpiyskiy stadion Luzhniki (Neutral Site)
                     2018-07-14 Belgium-England                     Gazprom Arena (Neutral Site)
                     2018-07-15 France-Croatia       Olimpiyskiy stadion Luzhniki (Neutral Site)

                                                              referee  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia     Néstor Pitana
                     2018-06-15 Egypt-Uruguay           Björn Kuipers
                     2018-06-15 Morocco-IR Iran          Cüneyt Çakιr
                     2018-06-15 Portugal-Spain        Gianluca Rocchi
                     2018-06-16 Argentina-Iceland    Szymon Marciniak
...                                                               ...
                     2018-07-07 Sweden-England          Björn Kuipers
                     2018-07-10 France-Belgium           Andrés Cunha
                     2018-07-11 Croatia-England          Cüneyt Çakιr
                     2018-07-14 Belgium-England       Alireza Faghani
                     2018-07-15 France-Croatia          Néstor Pitana

                                                                                          match_report  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia  /en/matches/c9d7e48c/Russia-Saudi-Arabia-June-...
                     2018-06-15 Egypt-Uruguay        /en/matches/cea695e1/Egypt-Uruguay-June-15-201...
                     2018-06-15 Morocco-IR Iran      /en/matches/028c7b0f/Morocco-IR-Iran-June-15-2...
                     2018-06-15 Portugal-Spain       /en/matches/2fecb1be/Portugal-Spain-June-15-20...
                     2018-06-16 Argentina-Iceland    /en/matches/1b352279/Argentina-Iceland-June-16...
...                                                                                                ...
                     2018-07-07 Sweden-England       /en/matches/c7b2bf0a/Sweden-England-July-7-201...
                     2018-07-10 France-Belgium       /en/matches/605079c0/France-Belgium-July-10-20...
                     2018-07-11 Croatia-England      /en/matches/12d32bfa/Croatia-England-July-11-2...
                     2018-07-14 Belgium-England      /en/matches/bc417615/Belgium-England-July-14-2...
                     2018-07-15 France-Croatia       /en/matches/a7957cf1/France-Croatia-July-15-20...

                                                                   notes  \
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia                 <NA>
                     2018-06-15 Egypt-Uruguay                       <NA>
                     2018-06-15 Morocco-IR Iran                     <NA>
                     2018-06-15 Portugal-Spain                      <NA>
                     2018-06-16 Argentina-Iceland                   <NA>
...                                                                  ...
                     2018-07-07 Sweden-England                      <NA>
                     2018-07-10 France-Belgium                      <NA>
                     2018-07-11 Croatia-England      Required Extra Time
                     2018-07-14 Belgium-England                     <NA>
                     2018-07-15 France-Croatia                      <NA>

                                                      game_id
league        season game
INT-World Cup 2018   2018-06-14 Russia-Saudi Arabia  c9d7e48c
                     2018-06-15 Egypt-Uruguay        cea695e1
                     2018-06-15 Morocco-IR Iran      028c7b0f
                     2018-06-15 Portugal-Spain       2fecb1be
                     2018-06-16 Argentina-Iceland    1b352279
...                                                       ...
                     2018-07-07 Sweden-England       c7b2bf0a
                     2018-07-10 France-Belgium       605079c0
                     2018-07-11 Croatia-England      12d32bfa
                     2018-07-14 Belgium-England      bc417615
                     2018-07-15 France-Croatia       a7957cf1

[64 rows x 14 columns]

*Estatísticas das partidas dos jogadores*

In [60]:
player_match_stats = fbref.read_player_match_stats(stat_type = "summary", match_id = "a7957cf1")
player_match_stats

[05/29/26 16:26:05] INFO     [1/1] Retrieving game with id=a7957cf1                                    ]8;id=365633;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=352629;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\site-packages\soccerdata\fbref.py#765\765]8;;\

[05/29/26 16:26:17] WARNING  c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\L ]8;id=544726;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=848198;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             ib\site-packages\soccerdata\fbref.py:776: FutureWarning: This
                             search incorrectly ignores the root element, and will be fixed in
                             a future version.  If you rely on the current behaviour, change it
                             to ".//table"
                               html_table = tree.find("//table[@id='" +
                             id_format.format(home_team["id"]) + "']")

                    WARNING  c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\L ]8;id=715674;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py\_py_warnings.py]8;;\:]8;id=106451;file://c:\Users\raphael.eugenio\AppData\Local\Programs\Python\Python314\Lib\_py_warnings.py#230\230]8;;\
                             ib\site-packages\soccerdata\fbref.py:787: FutureWarning: This
                             search incorrectly ignores the root element, and will be fixed in
                             a future version.  If you rely on the current behaviour, change it
                             to ".//table"
                               html_table = tree.find("//table[@id='" +
                             id_format.format(away_team["id"]) + "']")

                                                                         jersey_number  \

league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić               9
                                                       Ante Rebić                   18
                                                       Danijel Subašić              23
                                                       Dejan Lovren                  6
                                                       Domagoj Vida                 21
                                                       Ivan Perišić                  4
                                                       Ivan Rakitić                  7
                                                       Ivan Strinić                  3
                                                       Luka Modrić                  10
                                                       Marcelo Brozović             11
                                                       Mario Mandžukić              17
                                                       Marko Pjaca                  20
                                                       Šime Vrsaljko                 2
                                               France  Antoine Griezmann             7
                                                       Benjamin Pavard               2
                                                       Blaise Matuidi               14
                                                       Corentin Tolisso             12
                                                       Hugo Lloris                   1
                                                       Kylian Mbappé                10
                                                       Lucas Hernández              21
                                                       N'Golo Kanté                 13
                                                       Nabil Fekir                  18
                                                       Olivier Giroud                9
                                                       Paul Pogba                    6
                                                       Raphaël Varane                4
                                                       Samuel Umtiti                 5
                                                       Steven Nzonzi                15

                                                                            pos  \

league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić    FW,MF
                                                       Ante Rebić            AM
                                                       Danijel Subašić       GK
                                                       Dejan Lovren          CB
                                                       Domagoj Vida          CB
                                                       Ivan Perišić          AM
                                                       Ivan Rakitić          DM
                                                       Ivan Strinić          LB
                                                       Luka Modrić           AM
                                                       Marcelo Brozović      DM
                                                       Mario Mandžukić       FW
                                                       Marko Pjaca        FW,MF
                                                       Šime Vrsaljko         RB
                                               France  Antoine Griezmann     AM
                                                       Benjamin Pavard       RB
                                                       Blaise Matuidi        AM
                                                       Corentin Tolisso   DF,MF
                                                       Hugo Lloris           GK
                                                       Kylian Mbappé         AM
                                                       Lucas Hernández       LB
                                                       N'Golo Kanté          DM
                                                       Nabil Fekir        FW,MF
                                                       Olivier Giroud        FW
                                                       Paul Pogba            DM
                                                       Raphaël Varane        CB
                                                       Samuel Umtiti         CB
                                                       Steven Nzonzi         MF

                                                                             age  \

league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić    27-026
                                                       Ante Rebić         24-297
                                                       Danijel Subašić    33-261
                                                       Dejan Lovren       29-010
                                                       Domagoj Vida       29-077
                                                       Ivan Perišić       29-163
                                                       Ivan Rakitić       30-127
                                                       Ivan Strinić       30-363
                                                       Luka Modrić        32-309
                                                       Marcelo Brozović   25-241
                                                       Mario Mandžukić    32-055
                                                       Marko Pjaca        23-070
                                                       Šime Vrsaljko      26-186
                                               France  Antoine Griezmann  27-116
                                                       Benjamin Pavard    22-109
                                                       Blaise Matuidi     31-097
                                                       Corentin Tolisso   23-346
                                                       Hugo Lloris        31-201
                                                       Kylian Mbappé      19-207
                                                       Lucas Hernández    22-151
                                                       N'Golo Kanté       27-108
                                                       Nabil Fekir        24-362
                                                       Olivier Giroud     31-288
                                                       Paul Pogba         25-122
                                                       Raphaël Varane     25-081
                                                       Samuel Umtiti      24-243
                                                       Steven Nzonzi      29-212

                                                                         min  \

league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić    20
                                                       Ante Rebić         70
                                                       Danijel Subašić    90
                                                       Dejan Lovren       90
                                                       Domagoj Vida       90
                                                       Ivan Perišić       90
                                                       Ivan Rakitić       90
                                                       Ivan Strinić       81
                                                       Luka Modrić        90
                                                       Marcelo Brozović   90
                                                       Mario Mandžukić    90
                                                       Marko Pjaca         9
                                                       Šime Vrsaljko      90
                                               France  Antoine Griezmann  90
                                                       Benjamin Pavard    90
                                                       Blaise Matuidi     72
                                                       Corentin Tolisso   18
                                                       Hugo Lloris        90
                                                       Kylian Mbappé      90
                                                       Lucas Hernández    90
                                                       N'Golo Kanté       53
                                                       Nabil Fekir        10
                                                       Olivier Giroud     80
                                                       Paul Pogba         90
                                                       Raphaël Varane     90
                                                       Samuel Umtiti      90
                                                       Steven Nzonzi      37

                                                                         Performance  \
                                                                                 Gls
league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić             0
                                                       Ante Rebić                  0
                                                       Danijel Subašić             0
                                                       Dejan Lovren                0
                                                       Domagoj Vida                0
                                                       Ivan Perišić                1
                                                       Ivan Rakitić                0
                                                       Ivan Strinić                0
                                                       Luka Modrić                 0
                                                       Marcelo Brozović            0
                                                       Mario Mandžukić             1
                                                       Marko Pjaca                 0
                                                       Šime Vrsaljko               0
                                               France  Antoine Griezmann           1
                                                       Benjamin Pavard             0
                                                       Blaise Matuidi              0
                                                       Corentin Tolisso            0
                                                       Hugo Lloris                 0
                                                       Kylian Mbappé               1
                                                       Lucas Hernández             0
                                                       N'Golo Kanté                0
                                                       Nabil Fekir                 0
                                                       Olivier Giroud              0
                                                       Paul Pogba                  1
                                                       Raphaël Varane              0
                                                       Samuel Umtiti               0
                                                       Steven Nzonzi               0

                                                                              \
                                                                         Ast
league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić     0
                                                       Ante Rebić          0
                                                       Danijel Subašić     0
                                                       Dejan Lovren        0
                                                       Domagoj Vida        1
                                                       Ivan Perišić        0
                                                       Ivan Rakitić        0
                                                       Ivan Strinić        0
                                                       Luka Modrić         0
                                                       Marcelo Brozović    0
                                                       Mario Mandžukić     0
                                                       Marko Pjaca         0
                                                       Šime Vrsaljko       0
                                               France  Antoine Griezmann   0
                                                       Benjamin Pavard     0
                                                       Blaise Matuidi      0
                                                       Corentin Tolisso    0
                                                       Hugo Lloris         0
                                                       Kylian Mbappé       0
                                                       Lucas Hernández     1
                                                       N'Golo Kanté        0
                                                       Nabil Fekir         0
                                                       Olivier Giroud      0
                                                       Paul Pogba          0
                                                       Raphaël Varane      0
                                                       Samuel Umtiti       0
                                                       Steven Nzonzi       0

                                                                             \
                                                                         PK
league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić    0
                                                       Ante Rebić         0
                                                       Danijel Subašić    0
                                                       Dejan Lovren       0
                                                       Domagoj Vida       0
                                                       Ivan Perišić       0
                                                       Ivan Rakitić       0
                                                       Ivan Strinić       0
                                                       Luka Modrić        0
                                                       Marcelo Brozović   0
                                                       Mario Mandžukić    0
                                                       Marko Pjaca        0
                                                       Šime Vrsaljko      0
                                               France  Antoine Griezmann  1
                                                       Benjamin Pavard    0
                                                       Blaise Matuidi     0
                                                       Corentin Tolisso   0
                                                       Hugo Lloris        0
                                                       Kylian Mbappé      0
                                                       Lucas Hernández    0
                                                       N'Golo Kanté       0
                                                       Nabil Fekir        0
                                                       Olivier Giroud     0
                                                       Paul Pogba         0
                                                       Raphaël Varane     0
                                                       Samuel Umtiti      0
                                                       Steven Nzonzi      0

                                                                                \
                                                                         PKatt
league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić       0
                                                       Ante Rebić            0
                                                       Danijel Subašić       0
                                                       Dejan Lovren          0
                                                       Domagoj Vida          0
                                                       Ivan Perišić          0
                                                       Ivan Rakitić          0
                                                       Ivan Strinić          0
                                                       Luka Modrić           0
                                                       Marcelo Brozović      0
                                                       Mario Mandžukić       0
                                                       Marko Pjaca           0
                                                       Šime Vrsaljko         0
                                               France  Antoine Griezmann     1
                                                       Benjamin Pavard       0
                                                       Blaise Matuidi        0
                                                       Corentin Tolisso      0
                                                       Hugo Lloris           0
                                                       Kylian Mbappé         0
                                                       Lucas Hernández       0
                                                       N'Golo Kanté          0
                                                       Nabil Fekir           0
                                                       Olivier Giroud        0
                                                       Paul Pogba            0
                                                       Raphaël Varane        0
                                                       Samuel Umtiti         0
                                                       Steven Nzonzi         0

                                                                             \
                                                                         Sh
league        season game                      team    player
INT-World Cup 2018   2018-07-15 France-Croatia Croatia Andrej Kramarić    0
                                                       Ante Rebić         3
                                                       Danijel Subašić    0
                                                       Dejan Lovren       1
                                                       Domagoj Vida       2
                                                       Ivan Perišić       2
                                                       Ivan Rakitić       3
                                                       Ivan Strinić       0
                                                       Luka Modrić        0
                                                       Marcelo Brozović   0
                                                       Mario Mandžukić    1
                                                       Marko Pjaca        0