*Importando o Pandas*

In [160]:
import pandas as pd
import numpy as np

#definindo quantidade de linhas e colunas visiveis
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

*Importação de arquivos EXCEL*

In [161]:
hospital = 'SANTA_ISABEL'
mes = 'ABR'
caminho_importacao = ('G:/Drives compartilhados/Qualidade/ACURÁCIA/CATE 3136/2026/04 - ABR/')
df = pd.read_excel(caminho_importacao + 'CATE3136_' + hospital + '_' + mes + '26.xlsx')
df_bck = df.copy()

In [162]:
df['Cor'] = ''

In [163]:
df['Cor'].value_counts()

Cor
    842
Name: count, dtype: int64

In [164]:
hemo = df['Setor/Sala'].str.contains('Hemodinâmica', case=False, na=False)
df.loc[hemo, 'Cor'] = ''
df[hemo].head()

,þÿNr atendimento,Dt Internacao,Dt alta,Nm paciente,Dt nascimento,Idade,Sexo,Ds email,Nr telefone,Nr prescricao,Nr cirurgia,Ds tipo cirurgia,Porte,COD. TUSS,Ds procedimento,Proced adicional,Início previsto,Dt cirurgia,Dt termino,Nm cirurgiao,Duração Prevista,Duração Real,Ds especialidade cirurgiao,Nm anestesista,Tipo Anestesia,Asa,Cid doenca,Ds cid,Cid definitivo,Ds cid def,Tipo Posição,Superfície de Suporte,Posição Membros,Pontuação Elpo,Carater Cirurgia,Setor/Sala,CPF,Crm,Convenio,hr_inicio_antimicrobiano,hr_final_antimicrobiano,Antimicrobiano,Cor
5,53120684,2026-03-12 11:56:00,2026-04-03 00:00:00,Robert Mark Silva Hester,1960-08-13,66,Masculino,assistema@uol.com.br,Fone_I: 21 999033344; Fone Adc.: +55 933273344,117713881,1915157,Não se aplica,Médio,30911079,Cateterismo Cardíaco E E/Ou D Com Cineangiocor...,Avaliação Fisiológica da Gravidade de Obstruçõ...,2026-04-01 08:00:00,2026-04-01 09:05:00,2026-04-01 12:15:00,Marcio Eduardo de Rezende,90,190,Cardiologia intervencionista,Eduardo Arbache Bezerra,Loc+Sedação,"III - Com doença sistêmica grave, com limitaçã...",C182,NEOPLASIA MALIGNA DO COLON ASCENDENTE,C182,NEOPLASIA MALIGNA DO COLON ASCENDENTE,Supina,elevação dos joelhos > 90º e aberturas dos mem...,sem uso de superfície de suporte ou suportes r...,17 - Risco Menor,Urgência,Hemodinâmica - HSI HEMO01,69738530725,202232,Sul América,,,,
12,53542671,2026-03-30 19:03:00,2026-04-03 00:00:00,Josina Santos Silveira,1967-07-09,59,Feminino,josyhair01@gmail.com,Fone_I: 11 913722716; Fone_II: 11 966360615; F...,117713888,1915158,Limpa,Médio,30911028,Avaliação Fisiológica Da Gravidade De Obstruçõ...,Cateterismo de Câmaras Cardíacas Esquerdas E C...,2026-04-01 11:00:00,2026-04-01 13:30:00,2026-04-01 16:45:00,Marcio Eduardo de Rezende,120,195,Cardiologia intervencionista,Izabela Camila Souza Ferreira,Sedação,II - Com doença sistêmica discreta,I255,MIOCARDIOPATIA ISQUEMICA,I255,MIOCARDIOPATIA ISQUEMICA,Supina,elevação dos joelhos > 90º e aberturas dos mem...,sem uso de superfície de suporte ou suportes r...,14 - Risco Menor,Urgência,Hemodinâmica - HSI HEMO01,10195597800,202232,BRADESCO SEGUR,,,,
18,53588769,2026-04-01 12:44:00,2026-04-17 00:00:00,Josias Bernardo de Lima,1952-06-26,74,Masculino,josias.bernardo26@gmail.com,Fone_I: 11 970245070; Fone_II: 11 970245070;,117731556,1915497,Limpa,Médio,40813070,Angioplastia De Tronco Supra-Aórtico,Tratamento Cirúrgico da Isquemia Cerebral; Ang...,2026-04-01 16:30:00,2026-04-01 17:00:00,2026-04-01 19:20:44,Bernardo Paiva Hime,90,141,Cirurgia Vascular,Francisco Jose Lucena Bezerra,Geral,II - Com doença sistêmica discreta,I652,OCLUSAO E ESTENOSE DA ARTERIA CAROTIDA,I652,OCLUSAO E ESTENOSE DA ARTERIA CAROTIDA,Supina,posição anatômica,colchão da mesa cirúrgica de vicoelástico + co...,17 - Risco Menor,Eletiva,Hemodinâmica - HSI HEMO01,5127663805,192561,Mediservice,17:20:00,17:20:00,CEFAZOLINA 1G FA ABL.,
52,53620496,2026-04-02 15:15:00,2026-04-03 00:00:00,Dulce Rodrigues Levy,1975-03-09,51,Feminino,dulcerodriguescamargo0@gmail.com,Fone_I: 11 986833287; Fone_II: 11 986833287; F...,117821586,1916512,Potencialmente Contaminada,Pequeno,40814084,Retirada Percutânea De Corpo Estranho Intravas...,Angiografia Transoperatória de Posicionamento ...,2026-04-02 19:00:00,2026-04-02 19:05:00,2026-04-02 20:40:00,Bernardo Paiva Hime,60,95,Cirurgia Vascular,Raphael Moura Britto,Geral,II - Com doença sistêmica discreta,I82,OUTRA EMBOLIA E TROMBOSE VENOSAS,I82,OUTRA EMBOLIA E TROMBOSE VENOSAS,Supina,posição anatômica,colchão da mesa cirúrgica de vicoelástico + co...,15 - Risco Menor,Eletiva,Hemodinâmica - HSI HEMO01,18516701816,192561,Sul América,19:15:00,19:15:00,CEFAZOLINA 1G FA ABL.,
67,53628594,2026-04-03 06:39:00,2026-04-03 00:00:00,Aloma Oliveira dos Santos Brandassi,1991-10-31,35,Feminino,alomaoliveira31@gmail.com,Fone_I: 11 961076356; Fone_II: 11 993258659; F...,117844657,1916922,Não se aplica,Médio,40812057,Angiografia Por Cateterismo Superseletivo De R...,Curativo Especial Sob Anestesia - Por Unidade ...,2026-04-03 09:00:00,2026-04-03 11:30:00,2026-04-03 13:10:56,Guilherme Brasileiro de Aguiar,60,101,Neurocirurgia,Flavio Rosa Figueiredo Souza,Geral,II - Com doença sistêmica discreta,I670,"DISSECCAO DE ARTERIAS CEREBRAIS, SEM RUPTURA",I670,"DISSECCAO DE ARTERIAS CEREBRAIS, SEM RUPTURA",Supina,elevação dos joelhos < 90º e abertura dos memb...,colchão da mesa cirúrgica de espuma (convencio...,13 - Risco Menor,Eletiva,Hemodinâmica - HSI HEMO01,36632075878,137419,Sul América,,,,

In [165]:
df['Setor/Sala'].value_counts()
df['Setor/Sala'].str.contains('Centro Cirurgico|Centro Obstétrico|CO|CC', case=False, na=False)

0       True
1       True
2       True
3       True
4       True
       ...
837     True
838     True
839     True
840     True
841    False
Name: Setor/Sala, Length: 842, dtype: bool

In [166]:
verde = df['Setor/Sala'].str.contains('Centro Cirurgico|Centro Obstétrico|CO|CC', case=False, na=False)
df.loc[verde, 'Cor'] = 'Verde'

print(df[df['Setor/Sala'].str.contains('Centro Cirurgico|Centro Obstétrico|CO|CC', case=False, na=False)])

     þÿNr atendimento       Dt Internacao                    Dt alta  \
0            53573462 2026-03-31 20:41:00        2026-04-02 00:00:00
1            53575531 2026-04-01 04:37:00        2026-04-01 00:00:00
2            53575642 2026-04-01 05:14:00        2026-04-02 00:00:00
3            53514613 2026-03-29 22:36:00        2026-04-04 00:00:00
4            53573757 2026-03-31 21:11:00        2026-04-01 00:00:00
..                ...                 ...                        ...
836          54227070 2026-04-30 06:40:00        2026-04-30 00:00:00
837          54241865 2026-04-30 13:55:00        2026-04-30 00:00:00
838          54187221 2026-04-28 15:07:00        2026-05-01 00:00:00
839          54240998 2026-04-30 13:31:00        2026-05-01 00:00:00
840          54006595 2026-04-20 17:18:00

                         Nm paciente Dt nascimento  Idade       Sexo  \
0              Jose dos Santos Cunha    1960-06-06     66  Masculino
1                       Ivanil Nunes    1966-02-09     60  Masculino
2    Patrícia Abreu Alcaraz da Silva    1983-02-14     43   Feminino
3               Jose Augusto Baraldi    1952-03-19     74  Masculino
4              Edineti Pulz de Faria    1962-02-24     64   Feminino
..                               ...           ...    ...        ...
836             Armando Coelho Gomes    1941-03-02     85  Masculino
837          Danilo Costa dos Santos    1992-04-15     34  Masculino
838         Carla de Souza Moya Rios    1969-07-22     57   Feminino
839        Fabio Henrique Luz Santos    2005-09-17     21  Masculino
840         Robert Mark Silva Hester    1960-08-13     66  Masculino

                        Ds email  \
0            cunha6060@gmail.com
1        ivanil09nunes@gmail.com
2          patyalcaraz@gmail.com
3       augustobaraldi@gmail.com
4          edi_pulz@yahoo.com.br
..                           ...
836        eduflemming@gmail.com
837
838    carlinharios644@gmail.com
839      silmara.luz@hotmail.com
840         assistema@uol.com.br

                                           Nr telefone Nr prescricao  \
0        Fone_I: 11 958700348; Fone_II: 11 958700348;      117688140
1    Fone_I: 11 998196036; Fone_II: 11 979621481; F...     117705963
2                               Fone_I: 11 980272689;      117706611
3    Fone_I: 11 949497170; Fone_II: 11 949497170; F...     117705001
4        Fone_I: 11 989442421; Fone_II: 11 989442421;      117690168
..                                                 ...           ...
836      Fone_I: 11 986095933; Fone_II: 11 986095933;      119663891
837  Fone_I: 11 945340991; Fone_II: 11 945340991; F...     119636973
838  Fone_I: 11 954808541; Fone_II: 11 954808541; F...     119636974
839  Fone_I: 11 992188299; Fone_II: 11 992188299; F...     119636975
840     Fone_I: 21 999033344; Fone Adc.: +55 933273344     119636976

     Nr cirurgia            Ds tipo cirurgia     Porte  COD. TUSS  \
0        1914940                       Limpa    Grande   31201130
1        1914985                               Pequeno   31206220
2        1914988                       Limpa    Grande   31403182
3        1914939                       Limpa     Médio   30904145
4        1914938                       Limpa     Médio   31403239
..           ...                         ...       ...        ...
836      1938961  Potencialmente Contaminada     Médio   40202038
837      1938467                              Especial   30208149
838      1938468                 Contaminada     Médio   31403034
839      1938469                       Limpa   Pequeno   31009336
840      1938470                       Limpa   Pequeno   30913101

                                       Ds procedimento  \
0                    Ressecção Endoscópica Da Próstata
1                                          Postectomia
2    Microcirurgia Do Plexo Braquial Com Exploração...
3    Implante De Marca-Passo Bicameral (Gerador + E...
4                                 Microneurólise Única
..                                                 ...
836  Endoscopia Digestiva Alta Com Biópsia E/Ou Cit...
837  Tratamento Cir ou Artroplastia para Luxação da...
838  Denervação Percutânea De Faceta Articular - Po...
839  Herniorrafia Inguinal - Unilateral Por Videola...
840  Implante Cirúrgico De Cateter De Longa Permanê...

                                      Proced adicional     Início previsto  \
0      Uretroplastia Anterior; Uretroplastia Posterior 2026-04-01 06:00:00
1    Extensos Ferimentos, Cicatrizes ou Tumores - R... 2026-04-01 07:30:00
2    Síndrome do Desfiladeiro Cérvico Torácico - Tr... 2026-04-01 07:30:00
3    Avaliação Clínica E Eletrônica de Paciente Por... 2026-04-01 07:00:00
4    Artrodese do Tarso; Osteotomia Ou Pseudartrose... 2026-04-01 08:00:00
..                                                 ...                 ...
836                  Hemostasia Termica Por Endoscopia 2026-04-30 13:30:00
837                                                    2026-04-30 14:30:00
838      Denervação Percutânea das Facetas Articulares 2026-04-30 16:00:00
839                                                    2026-04-30 16:30:00
840  Bloqueio de Nervo Periférico; Radioscopia Para... 2026-04-30 20:00:00

            Dt cirurgia           Dt termino  \
0   2026-04-01 06:30:00  2026-04-01 07:40:13
1   2026-04-01 07:44:00  2026-04-01 09:15:43
2   2026-04-01 07:55:00  2026-04-01 10:20:43
3   2026-04-01 08:00:00  2026-04-01 10:22:11
4   2026-04-01 09:00:00  2026-04-01 13:00:59
..                  ...                  ...
836 2026-04-30 15:35:00  2026-04-30 16:30:25
837 2026-04-30 15:50:00  2026-04-30 17:30:00
838 2026-04-30 16:45:00  2026-04-30 17:35:00
839 2026-04-30 17:00:00  2026-04-30 20:11:04
840 2026-04-30 18:50:00  2026-04-30 19:22:39

                                Nm cirurgiao  Duração Prevista Duração Real  \
0                Manuela Horta Martins Penna                90           70
1                Manuela Horta Martins Penna               120           91
2                      RICARDO AMARAL GURGEL                90          146
3               Italo Bruno dos Santos Sousa                90          142
4                   Fausto Santana Celestino                90          241
..                                       ...               ...          ...
836  Marina Tucci Gammaro Baldavira Ferreira                60           55
837                  Fabio Augusto Cozzolino                60           99
838                             Robert Meves                60           50
839                    Jose Gustavo Parreira                60          190
840                      Bruno Maltese Zuffo                60           32

      Ds especialidade cirurgiao                   Nm anestesista  \
0                       Urologia   Victor Augusto de Souza Moraes
1                       Urologia                   Kaie Fernandes
2              Cirurgia Vascular          Luciano Angelo Richetti
3                    Cardiologia    Izabela Camila Souza Ferreira
4      Ortopedia e Traumatologia  Leandro Oliveira Martins Cortes
..                           ...                              ...
836               Cirurgia Geral  Leandro Oliveira Martins Cortes
837  Cirurgia Buco Maxilo Facial           Marcelo dos Anjos Reis
838    Ortopedia e Traumatologia
839           Cirurgia de Trauma        Luiz Felipe Nobre Queiroz
840            Cirurgia Vascular

    Tipo Anestesia                                                Asa  \
0            Geral                 II - Com doença sistêmica discreta
1            Geral                 II - Com doença sistêmica discreta
2            Geral                 II - Com doença sistêmica discreta
3            Geral                 II - Com doença sistêmica discreta
4            Geral                 II - Com doença sistêmica discreta
..             ...                                                ...
836        Sedação  III - Com doença sistêmica grave, com limitaçã...
837          Geral                                       I - Saudável
838          Local                                       I - Saudável
839          Geral                                       I - Saudável
840          Local                 II - Com doença sistêmica discreta

    Cid doenca                                             Ds cid  \
0          N35                                 ESTENOSE DA URETRA
1          N47       HIPERTROFIA DO PREPUCIO, FIMOSE E PARAFIMOSE
2          G54       TRANSTORNOS DAS RAIZES E DOS PLEXOS NERVOSOS
3         Z950                   PRESENCA DE MARCA-PASSO CARDIACO
4         Z540                        CONVALESCENCA APOS CIRURGIA
..         ...                                                ...
836       K928  OUTRAS DOENCAS ESPECIFICADAS DO APARELHO DIGES...
837        K07    ANOMALIAS DENTOFACIAIS (INCLUSIVE A MALOCLUSAO)
838       M545                                   DOR LOMBAR BAIXA
839        K40                                    HERNIA INGUINAL
840        R53                                  MAL ESTAR, FADIGA

                Cid definitivo  \
0                          N35
1                          N47
2                          G54
3                         Z950
4                         Z540
..                         ...
836                       K928
837                        K07
838                       M545
839                        K40
840

                                            Ds cid def  \
0                                   ESTENOSE DA URETRA
1         HIPERTROFIA DO PREPUCIO, FIMOSE E PARAFIMOSE
2         TRANSTORNOS DAS RAIZES E DOS PLEXOS NERVOSOS
3                     PRESENCA DE MARCA-PASSO CARDIACO
4                          CONVALESCENCA APOS CIRURGIA
..                                                 ...
836  OUTRAS DOENCAS ESPECIFICADAS DO APARELHO DIGES...
837    ANOMALIAS DENTOFACIAIS (INCLUSIVE A MALOCLUSAO)
838                                   DOR LOMBAR BAIXA
839                                    HERNIA INGUINAL
840

                  Tipo Posição  \
0                   Litotômica
1                       Supina
2                       Supina
3                       Supina
4                      Lateral
..                         ...
836
837                     Supina
838                      Prona
839                     Supina
840                     Supina

                                 Superfície de Suporte  \
0                                    posição anatômica
1                                    posição anatômica
2                                    posição anatômica
3    elevação dos joelhos > 90º e aberturas dos mem...
4                                    posição anatômica
..                                                 ...
836
837  elevação dos joelhos < 90º e abertura dos memb...
838                                  posição anatômica
839  elevação dos joelhos < 90º e abertura dos memb...
840  elevação dos joelhos < 90º e abertura dos memb...

                                       Posição Membros  \
0    colchão da mesa cirúrgica de vicoelástico + co...
1    colchão da mesa cirúrgica de vicoelástico + co...
2    colchão da mesa cirúrgica de vicoelástico + co...
3    sem uso de superfície de suporte ou suportes r...
4    colchão da mesa cirúrgica de vicoelástico + co...
..                                                 ...
836
837  colchão da mesa cirúrgica de espuma (convencio...
838  colchão da mesa cirúrgica de vicoelástico + co...
839  colchão da mesa cirúrgica de espuma (convencio...
840  colchão da mesa cirúrgica de espuma (convencio...

                Pontuação Elpo Carater Cirurgia  \
0             21 - Risco Maior          Eletiva
1             14 - Risco Menor          Eletiva
2             12 - Risco Menor          Eletiva
3             17 - Risco Menor          Eletiva
4             13 - Risco Menor          Eletiva
..                         ...              ...
836                                    Urgência
837           13 - Risco Menor          Eletiva
838           13 - Risco Menor         Urgência
839           14 - Risco Menor          Eletiva
840           12 - Risco Menor         Urgência

                               Setor/Sala                        CPF     Crm  \
0       Centro Cirurgico - HSI  CC - 02                   3432364865  177015
1       Centro Cirurgico - HSI  CC - 03                   6919593823  177015
2       Centro Cirurgico - HSI  CC - 08                  31081117877   48602
3       Centro Cirurgico - HSI  CC - 07                  59205636800  160272
4       Centro Cirurgico - HSI  CC - 04                  10739600800  156471
..                                    ...                        ...     ...
836  Centro Cirurgico - HSI  EDA/COLO 1                  61418706868  183287
837     Centro Cirurgico - HSI  CC - 06                                70435
838     Centro Cirurgico - HSI  CC - 03                   9500958856   77448
839     Centro Cirurgico - HSI  CC - 02                  53069588859   78316
840     Centro Cirurgico - HSI  CC - 03                  69738530725  192056

            Convenio   hr_inicio_antimicrobiano    hr_final_antimicrobiano  \
0     BRADESCO SEGUR                   06:35:00                   06:35:00
1     BRADESCO SEGUR                   08:00:00                   08:00:00
2        Unimed Fesp                   08:06:00                   08:06:00
3              Cassi                   08:10:00                   08:10:00
4        Sul América                   09:29:00                   09:29:00
..               ...                        ...                        ...
836  BRADESCO OPERAD
837      Sul América                   16:00:00                   16:00:00
838      Sul América
839      Sul América                   17:11:00                   17:11:00
840      Sul América

                    Antimicrobiano    Cor
0                 ROCEFIN 1G IV FA  Verde
1            CEFAZOLINA 1G FA ABL.  Verde
2     CLINDAMICINA 600MG/4ML AMP .  Verde
3    CEFUROXIMA 750MG FA AUROBINDO  Verde
4            CEFAZOLINA 1G FA ABL.  Verde
..                             ...    ...
836                                 Verde
837          CEFAZOLINA 1G FA ABL.  Verde
838                                 Verde
839          CEFAZOLINA 1G FA ABL.  Verde
840                                 Verde

[809 rows x 43 columns]

*Obtendo nomes das colunas*

In [167]:
df.columns

Index(['þÿNr atendimento', 'Dt Internacao', 'Dt alta', 'Nm paciente',
       'Dt nascimento', 'Idade', 'Sexo', 'Ds email', 'Nr telefone',
       'Nr prescricao', 'Nr cirurgia', 'Ds tipo cirurgia', 'Porte',
       'COD. TUSS', 'Ds procedimento', 'Proced adicional', 'Início previsto',
       'Dt cirurgia', 'Dt termino', 'Nm cirurgiao', 'Duração Prevista',
       'Duração Real', 'Ds especialidade cirurgiao', 'Nm anestesista',
       'Tipo Anestesia', 'Asa', 'Cid doenca', 'Ds cid', 'Cid definitivo',
       'Ds cid def', 'Tipo Posição', 'Superfície de Suporte',
       'Posição Membros', 'Pontuação Elpo', 'Carater Cirurgia', 'Setor/Sala',
       'CPF', 'Crm', 'Convenio', 'hr_inicio_antimicrobiano',
       'hr_final_antimicrobiano', 'Antimicrobiano', 'Cor'],
      dtype='str')

*Remover linhas que não contem resposta*

In [168]:
condicao = (
    df['Tipo Anestesia'].str.strip().replace('', np.nan).isna() &
    df['Setor/Sala'].str.contains('Hemodinâmica', case=False, na=False)
)
df.loc[condicao, 'Tipo Anestesia'] = 'Sedação'
df[condicao].head()

Empty DataFrame
Columns: [þÿNr atendimento, Dt Internacao, Dt alta, Nm paciente, Dt nascimento, Idade, Sexo, Ds email, Nr telefone, Nr prescricao, Nr cirurgia, Ds tipo cirurgia, Porte, COD. TUSS, Ds procedimento, Proced adicional, Início previsto, Dt cirurgia, Dt termino, Nm cirurgiao, Duração Prevista, Duração Real, Ds especialidade cirurgiao, Nm anestesista, Tipo Anestesia, Asa, Cid doenca, Ds cid, Cid definitivo, Ds cid def, Tipo Posição, Superfície de Suporte, Posição Membros, Pontuação Elpo, Carater Cirurgia, Setor/Sala, CPF, Crm, Convenio, hr_inicio_antimicrobiano, hr_final_antimicrobiano, Antimicrobiano, Cor]
Index: []

*Filtrando os dados*

In [169]:
palavras = (
    'Local',
    'Local Assistida',
    'Sem analgesia'   
)

padrao = '|'.join(palavras)

vazios = (
    (df['Tipo Anestesia'].fillna('').str.strip().eq('')) |
    (df['Tipo Anestesia'].str.contains(padrao, case=False, na=False)) &
    df['Setor/Sala'].str.contains('Hemodinâmica', case=False, na=False)
)
df.loc[vazios, 'Cor'] = 'Amarelo'
df[vazios].head()

,þÿNr atendimento,Dt Internacao,Dt alta,Nm paciente,Dt nascimento,Idade,Sexo,Ds email,Nr telefone,Nr prescricao,Nr cirurgia,Ds tipo cirurgia,Porte,COD. TUSS,Ds procedimento,Proced adicional,Início previsto,Dt cirurgia,Dt termino,Nm cirurgiao,Duração Prevista,Duração Real,Ds especialidade cirurgiao,Nm anestesista,Tipo Anestesia,Asa,Cid doenca,Ds cid,Cid definitivo,Ds cid def,Tipo Posição,Superfície de Suporte,Posição Membros,Pontuação Elpo,Carater Cirurgia,Setor/Sala,CPF,Crm,Convenio,hr_inicio_antimicrobiano,hr_final_antimicrobiano,Antimicrobiano,Cor
35,53604473,2026-04-02 07:26:00,2026-04-03 00:00:00,Celiane Sousa da Silva,1974-11-28,52,Feminino,celianehsousa@gmail.com,Fone_I: 11 992228370; Fone_II: 11 992228370; F...,117778084,1915974,,Grande,31001360,Refluxo Gastroesofágico - Tratamento Cirúrgico...,Hérnia Diafragmática - Tratamento Cirúrgico Po...,2026-04-02 10:00:00,2026-04-02 10:50:00,2026-04-02 14:49:12,Adilson Costa Rodrigues Junior,120,239,Cirurgia do Aparelho Digestivo,Pedro Augusto Tavares Dall Aglio,,,K21,DOENCA DE REFLUXO GASTROESOFAGICO,K21,DOENCA DE REFLUXO GASTROESOFAGICO,Supina,elevação dos joelhos < 90º e abertura dos memb...,colchão da mesa cirúrgica de espuma (convencio...,14 - Risco Menor,Eletiva,Centro Cirurgico - HSI CC - 07,18669428830,129576,Sul América,11:07:00,11:07:00,CEFAZOLINA 1G FA ABL.,Amarelo
71,53634093,2026-04-03 12:25:00,2026-04-09 00:00:00,Jose Cesar Marcondes,1967-11-13,59,Masculino,josecesarmarcondes@gmail.com,Fone_I: 11 961842060; Fone_II: 11 961842060; F...,117866247,1916982,Não se aplica,Médio,30911079,Cateterismo de Câmaras Esquerdas com Estudo Ci...,Recanalização Arterial No Iam-angioplastia Pri...,2026-04-03 14:00:00,2026-04-03 13:20:00,2026-04-03 15:20:00,Marcio Eduardo de Rezende,120,120,Cardiologia intervencionista,Guilherme Petry Martins Pereira,Local Assistida,"III - Com doença sistêmica grave, com limitaçã...",I21,INFARTO AGUDO DO MIOCARDIO,I21,INFARTO AGUDO DO MIOCARDIO,Supina,abertura dos membros superiores < 90º,colchão da mesa cirúrgica de espuma (convencio...,9 - Risco Menor,Emergência,Hemodinâmica - HSI HEMO01,2849269816,202232,Porto Saude,,,,Amarelo
132,53689631,2026-04-06 23:05:00,2026-04-07 00:00:00,Antonio Nicola Neto,1946-12-20,80,Masculino,,Fone_I: 11 999779694;,118067767,1918768,Limpa,Médio,30206120,Laringectomia Parcial,Laringotraqueoplastia,2026-04-07 05:00:00,2026-04-07 06:10:00,2026-04-07 09:28:20,Rafael Figueiredo dos Santos,120,198,Cirurgia de Cabeça e Pescoço,Guilherme Petry Martins Pereira,,,D020,CARCINOMA IN SITU DA LARINGE,D020,CARCINOMA IN SITU DA LARINGE,Supina,elevação dos joelhos < 90º e abertura dos memb...,colchão da mesa cirúrgica de espuma (convencio...,17 - Risco Menor,Eletiva,Centro Cirurgico - HSI CC - 01,5565634849,211462,Sul América,06:15:00,06:15:00,CEFAZOLINA 1G FA ABL.,Amarelo
144,53691739,2026-04-07 06:56:00,2026-04-09 00:00:00,Ricardo Geronimo Silva,1973-03-31,53,Masculino,,Fone_I: 11 985193102; Fone_II: 11 985193102; F...,118072850,1919053,,Grande,31201130,Ressecção Endoscópica Da Próstata,Colo Vesical - Ressecção Endoscópica; Uretropl...,2026-04-07 09:00:00,2026-04-07 10:05:00,2026-04-07 13:50:07,Marcelo Rodrigues Cabrini,60,225,Urologia,Pedro Augusto Tavares Dall Aglio,,,N40,HIPERPLASIA DA PROSTATA,N40,HIPERPLASIA DA PROSTATA,Supina,elevação dos joelhos < 90º e abertura dos memb...,colchão da mesa cirúrgica de espuma (convencio...,14 - Risco Menor,Eletiva,Centro Cirurgico - HSI CC - 08,,119761,Sul América,10:10:00,10:10:00,ROCEFIN 1G IV FA,Amarelo
150,53695679,2026-04-07 08:48:00,2026-04-07 00:00:00,Jocacia Ferreira dos Santos Cavalaro,1987-11-27,39,Feminino,jocacia_any3@yahoo.com.br,Fone_I: 11 990228649;,118081169,1919300,,Médio,31005470,Colecistectomia com Colangiografia,Herniorrafia Umbilical Convencional,2026-04-07 10:00:00,2026-04-07 12:40:00,2026-04-07 13:45:00,Michel Ribeiro Fernandes,60,65,Cirurgia do Aparelho Digestivo,Vinicius Souza Barbosa,,,K80,COLELITIASE,K80,COLELITIASE,Supina,abertura dos membros superiores < 90º,colchão da mesa cirúrgica de espuma (convencio...,13 - Risco Menor,Eletiva,Centro Cirurgico - HSI CC - 06,39384211850,220790,Notre Dame,12:51:00,12:51:00,CEFAZOLINA 1G FA ABL.,Amarelo

*Removendo caracteres indesejados*

In [170]:
len(df)

842

In [171]:
display(df_bck.loc[26:26])

display(df.loc[26:26])

,þÿNr atendimento,Dt Internacao,Dt alta,Nm paciente,Dt nascimento,Idade,Sexo,Ds email,Nr telefone,Nr prescricao,Nr cirurgia,Ds tipo cirurgia,Porte,COD. TUSS,Ds procedimento,Proced adicional,Início previsto,Dt cirurgia,Dt termino,Nm cirurgiao,Duração Prevista,Duração Real,Ds especialidade cirurgiao,Nm anestesista,Tipo Anestesia,Asa,Cid doenca,Ds cid,Cid definitivo,Ds cid def,Tipo Posição,Superfície de Suporte,Posição Membros,Pontuação Elpo,Carater Cirurgia,Setor/Sala,CPF,Crm,Convenio,hr_inicio_antimicrobiano,hr_final_antimicrobiano,Antimicrobiano
26,53601881,2026-04-01 23:13:00,2026-04-03 00:00:00,Jose Paulo de Oliveira,1970-06-04,56,Masculino,jpoliveira1970@gmail.com,Fone_I: 11 994175057; Fone Adc.: +55 989404242,117765556,1915829,Potencialmente Contaminada,Grande,31101569,Nefrectomia Parcial Laparoscópica Unilateral,Linfadenectomia Retroperitoneal Laparoscopica,2026-04-02 06:30:00,2026-04-02 07:00:00,2026-04-02 09:55:04,Marcio Rosa Pagan,180,174,Urologia,Felipe Costa de Albuquerque,Geral,II - Com doença sistêmica discreta,C64,"NEOPLASIA MALIGNA DO RIM, EXCETO PELVE RENAL",C64,"NEOPLASIA MALIGNA DO RIM, EXCETO PELVE RENAL",Supina,elevação dos joelhos < 90º e abertura dos memb...,colchão da mesa cirúrgica de espuma (convencio...,14 - Risco Menor,Eletiva,Centro Cirurgico - HSI CC - 08,16086644810,81944,Porto Saude,07:23:00,07:23:00,CEFAZOLINA 1G FA ABL.

,þÿNr atendimento,Dt Internacao,Dt alta,Nm paciente,Dt nascimento,Idade,Sexo,Ds email,Nr telefone,Nr prescricao,Nr cirurgia,Ds tipo cirurgia,Porte,COD. TUSS,Ds procedimento,Proced adicional,Início previsto,Dt cirurgia,Dt termino,Nm cirurgiao,Duração Prevista,Duração Real,Ds especialidade cirurgiao,Nm anestesista,Tipo Anestesia,Asa,Cid doenca,Ds cid,Cid definitivo,Ds cid def,Tipo Posição,Superfície de Suporte,Posição Membros,Pontuação Elpo,Carater Cirurgia,Setor/Sala,CPF,Crm,Convenio,hr_inicio_antimicrobiano,hr_final_antimicrobiano,Antimicrobiano,Cor
26,53601881,2026-04-01 23:13:00,2026-04-03 00:00:00,Jose Paulo de Oliveira,1970-06-04,56,Masculino,jpoliveira1970@gmail.com,Fone_I: 11 994175057; Fone Adc.: +55 989404242,117765556,1915829,Potencialmente Contaminada,Grande,31101569,Nefrectomia Parcial Laparoscópica Unilateral,Linfadenectomia Retroperitoneal Laparoscopica,2026-04-02 06:30:00,2026-04-02 07:00:00,2026-04-02 09:55:04,Marcio Rosa Pagan,180,174,Urologia,Felipe Costa de Albuquerque,Geral,II - Com doença sistêmica discreta,C64,"NEOPLASIA MALIGNA DO RIM, EXCETO PELVE RENAL",C64,"NEOPLASIA MALIGNA DO RIM, EXCETO PELVE RENAL",Supina,elevação dos joelhos < 90º e abertura dos memb...,colchão da mesa cirúrgica de espuma (convencio...,14 - Risco Menor,Eletiva,Centro Cirurgico - HSI CC - 08,16086644810,81944,Porto Saude,07:23:00,07:23:00,CEFAZOLINA 1G FA ABL.,Verde

In [172]:
caminho_exportacao = ("G:/Drives compartilhados/Qualidade/ACURÁCIA/INDICADORES HEMO/2026/ABR/")
df.to_excel(caminho_exportacao + 'HEMO_' + hospital + '_' + mes + '2026.xlsx')